// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/valuation/product_inputs.proto

package fintekkers.requests.valuation;

public interface CurvePointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintekkers.requests.valuation.CurvePoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Time from reference_date in years (e.g. 0.25, 0.5, 1.0, 2.0, 5.0, 10.0).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto tenor = 1;</code>
   * @return Whether the tenor field is set.
   */
  boolean hasTenor();
  /**
   * <pre>
   * Time from reference_date in years (e.g. 0.25, 0.5, 1.0, 2.0, 5.0, 10.0).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto tenor = 1;</code>
   * @return The tenor.
   */
  fintekkers.models.util.DecimalValue.DecimalValueProto getTenor();
  /**
   * <pre>
   * Time from reference_date in years (e.g. 0.25, 0.5, 1.0, 2.0, 5.0, 10.0).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto tenor = 1;</code>
   */
  fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getTenorOrBuilder();

  /**
   * <pre>
   * Continuously compounded zero rate as a decimal (e.g. 0.0425 = 4.25%).
   * Not a percentage — 4.25 would be interpreted as 425%.
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto rate = 2;</code>
   * @return Whether the rate field is set.
   */
  boolean hasRate();
  /**
   * <pre>
   * Continuously compounded zero rate as a decimal (e.g. 0.0425 = 4.25%).
   * Not a percentage — 4.25 would be interpreted as 425%.
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto rate = 2;</code>
   * @return The rate.
   */
  fintekkers.models.util.DecimalValue.DecimalValueProto getRate();
  /**
   * <pre>
   * Continuously compounded zero rate as a decimal (e.g. 0.0425 = 4.25%).
   * Not a percentage — 4.25 would be interpreted as 425%.
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto rate = 2;</code>
   */
  fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getRateOrBuilder();
}
