// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/valuation/product_inputs.proto

package fintekkers.requests.valuation;

/**
 * <pre>
 * ═══════════════════════════════════════════════════════════════════════════
 * FrnInput — valuation request for a Floating Rate Note.
 * Static security details (spread, reference_rate_index, coupon_frequency,
 * face_value, dated_date, maturity_date) are read from security.frn_details
 * and are not repeated here.
 * Settlement date is read from ValuationRequestProto.asof_datetime.
 * ═══════════════════════════════════════════════════════════════════════════
 * </pre>
 *
 * Protobuf type {@code fintekkers.requests.valuation.FrnInput}
 */
public final class FrnInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.requests.valuation.FrnInput)
    FrnInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FrnInput.newBuilder() to construct.
  private FrnInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FrnInput() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FrnInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_FrnInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_FrnInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.requests.valuation.FrnInput.class, fintekkers.requests.valuation.FrnInput.Builder.class);
  }

  public static final int SECURITY_FIELD_NUMBER = 1;
  private fintekkers.models.security.SecurityProto security_;
  /**
   * <pre>
   * The FRN security. Must have frn_details populated on the product_details oneof.
   * </pre>
   *
   * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
   * @return Whether the security field is set.
   */
  @java.lang.Override
  public boolean hasSecurity() {
    return security_ != null;
  }
  /**
   * <pre>
   * The FRN security. Must have frn_details populated on the product_details oneof.
   * </pre>
   *
   * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
   * @return The security.
   */
  @java.lang.Override
  public fintekkers.models.security.SecurityProto getSecurity() {
    return security_ == null ? fintekkers.models.security.SecurityProto.getDefaultInstance() : security_;
  }
  /**
   * <pre>
   * The FRN security. Must have frn_details populated on the product_details oneof.
   * </pre>
   *
   * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
   */
  @java.lang.Override
  public fintekkers.models.security.SecurityProtoOrBuilder getSecurityOrBuilder() {
    return security_ == null ? fintekkers.models.security.SecurityProto.getDefaultInstance() : security_;
  }

  public static final int CLEAN_PRICE_FIELD_NUMBER = 2;
  private fintekkers.models.util.DecimalValue.DecimalValueProto cleanPrice_;
  /**
   * <pre>
   * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
   * @return Whether the cleanPrice field is set.
   */
  @java.lang.Override
  public boolean hasCleanPrice() {
    return cleanPrice_ != null;
  }
  /**
   * <pre>
   * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
   * @return The cleanPrice.
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProto getCleanPrice() {
    return cleanPrice_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : cleanPrice_;
  }
  /**
   * <pre>
   * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getCleanPriceOrBuilder() {
    return cleanPrice_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : cleanPrice_;
  }

  public static final int CURVE_FIELD_NUMBER = 10;
  private fintekkers.requests.valuation.YieldCurveInput curve_;
  /**
   * <pre>
   * Yield curve for projecting floating coupons and discounting cashflows.
   * curve.index must match security.frn_details.reference_rate_index.
   * A single curve is used for both projection and discounting (single-curve framework).
   * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
   * </pre>
   *
   * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
   * @return Whether the curve field is set.
   */
  @java.lang.Override
  public boolean hasCurve() {
    return curve_ != null;
  }
  /**
   * <pre>
   * Yield curve for projecting floating coupons and discounting cashflows.
   * curve.index must match security.frn_details.reference_rate_index.
   * A single curve is used for both projection and discounting (single-curve framework).
   * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
   * </pre>
   *
   * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
   * @return The curve.
   */
  @java.lang.Override
  public fintekkers.requests.valuation.YieldCurveInput getCurve() {
    return curve_ == null ? fintekkers.requests.valuation.YieldCurveInput.getDefaultInstance() : curve_;
  }
  /**
   * <pre>
   * Yield curve for projecting floating coupons and discounting cashflows.
   * curve.index must match security.frn_details.reference_rate_index.
   * A single curve is used for both projection and discounting (single-curve framework).
   * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
   * </pre>
   *
   * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
   */
  @java.lang.Override
  public fintekkers.requests.valuation.YieldCurveInputOrBuilder getCurveOrBuilder() {
    return curve_ == null ? fintekkers.requests.valuation.YieldCurveInput.getDefaultInstance() : curve_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (security_ != null) {
      output.writeMessage(1, getSecurity());
    }
    if (cleanPrice_ != null) {
      output.writeMessage(2, getCleanPrice());
    }
    if (curve_ != null) {
      output.writeMessage(10, getCurve());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (security_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSecurity());
    }
    if (cleanPrice_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCleanPrice());
    }
    if (curve_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getCurve());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.requests.valuation.FrnInput)) {
      return super.equals(obj);
    }
    fintekkers.requests.valuation.FrnInput other = (fintekkers.requests.valuation.FrnInput) obj;

    if (hasSecurity() != other.hasSecurity()) return false;
    if (hasSecurity()) {
      if (!getSecurity()
          .equals(other.getSecurity())) return false;
    }
    if (hasCleanPrice() != other.hasCleanPrice()) return false;
    if (hasCleanPrice()) {
      if (!getCleanPrice()
          .equals(other.getCleanPrice())) return false;
    }
    if (hasCurve() != other.hasCurve()) return false;
    if (hasCurve()) {
      if (!getCurve()
          .equals(other.getCurve())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSecurity()) {
      hash = (37 * hash) + SECURITY_FIELD_NUMBER;
      hash = (53 * hash) + getSecurity().hashCode();
    }
    if (hasCleanPrice()) {
      hash = (37 * hash) + CLEAN_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getCleanPrice().hashCode();
    }
    if (hasCurve()) {
      hash = (37 * hash) + CURVE_FIELD_NUMBER;
      hash = (53 * hash) + getCurve().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.requests.valuation.FrnInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.valuation.FrnInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.requests.valuation.FrnInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.valuation.FrnInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.requests.valuation.FrnInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ═══════════════════════════════════════════════════════════════════════════
   * FrnInput — valuation request for a Floating Rate Note.
   * Static security details (spread, reference_rate_index, coupon_frequency,
   * face_value, dated_date, maturity_date) are read from security.frn_details
   * and are not repeated here.
   * Settlement date is read from ValuationRequestProto.asof_datetime.
   * ═══════════════════════════════════════════════════════════════════════════
   * </pre>
   *
   * Protobuf type {@code fintekkers.requests.valuation.FrnInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.requests.valuation.FrnInput)
      fintekkers.requests.valuation.FrnInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_FrnInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_FrnInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.requests.valuation.FrnInput.class, fintekkers.requests.valuation.FrnInput.Builder.class);
    }

    // Construct using fintekkers.requests.valuation.FrnInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      security_ = null;
      if (securityBuilder_ != null) {
        securityBuilder_.dispose();
        securityBuilder_ = null;
      }
      cleanPrice_ = null;
      if (cleanPriceBuilder_ != null) {
        cleanPriceBuilder_.dispose();
        cleanPriceBuilder_ = null;
      }
      curve_ = null;
      if (curveBuilder_ != null) {
        curveBuilder_.dispose();
        curveBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_FrnInput_descriptor;
    }

    @java.lang.Override
    public fintekkers.requests.valuation.FrnInput getDefaultInstanceForType() {
      return fintekkers.requests.valuation.FrnInput.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.requests.valuation.FrnInput build() {
      fintekkers.requests.valuation.FrnInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.requests.valuation.FrnInput buildPartial() {
      fintekkers.requests.valuation.FrnInput result = new fintekkers.requests.valuation.FrnInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fintekkers.requests.valuation.FrnInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.security_ = securityBuilder_ == null
            ? security_
            : securityBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cleanPrice_ = cleanPriceBuilder_ == null
            ? cleanPrice_
            : cleanPriceBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.curve_ = curveBuilder_ == null
            ? curve_
            : curveBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.requests.valuation.FrnInput) {
        return mergeFrom((fintekkers.requests.valuation.FrnInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.requests.valuation.FrnInput other) {
      if (other == fintekkers.requests.valuation.FrnInput.getDefaultInstance()) return this;
      if (other.hasSecurity()) {
        mergeSecurity(other.getSecurity());
      }
      if (other.hasCleanPrice()) {
        mergeCleanPrice(other.getCleanPrice());
      }
      if (other.hasCurve()) {
        mergeCurve(other.getCurve());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSecurityFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getCleanPriceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 82: {
              input.readMessage(
                  getCurveFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private fintekkers.models.security.SecurityProto security_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.security.SecurityProto, fintekkers.models.security.SecurityProto.Builder, fintekkers.models.security.SecurityProtoOrBuilder> securityBuilder_;
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     * @return Whether the security field is set.
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     * @return The security.
     */
    public fintekkers.models.security.SecurityProto getSecurity() {
      if (securityBuilder_ == null) {
        return security_ == null ? fintekkers.models.security.SecurityProto.getDefaultInstance() : security_;
      } else {
        return securityBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    public Builder setSecurity(fintekkers.models.security.SecurityProto value) {
      if (securityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        security_ = value;
      } else {
        securityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    public Builder setSecurity(
        fintekkers.models.security.SecurityProto.Builder builderForValue) {
      if (securityBuilder_ == null) {
        security_ = builderForValue.build();
      } else {
        securityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    public Builder mergeSecurity(fintekkers.models.security.SecurityProto value) {
      if (securityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          security_ != null &&
          security_ != fintekkers.models.security.SecurityProto.getDefaultInstance()) {
          getSecurityBuilder().mergeFrom(value);
        } else {
          security_ = value;
        }
      } else {
        securityBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    public Builder clearSecurity() {
      bitField0_ = (bitField0_ & ~0x00000001);
      security_ = null;
      if (securityBuilder_ != null) {
        securityBuilder_.dispose();
        securityBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    public fintekkers.models.security.SecurityProto.Builder getSecurityBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSecurityFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    public fintekkers.models.security.SecurityProtoOrBuilder getSecurityOrBuilder() {
      if (securityBuilder_ != null) {
        return securityBuilder_.getMessageOrBuilder();
      } else {
        return security_ == null ?
            fintekkers.models.security.SecurityProto.getDefaultInstance() : security_;
      }
    }
    /**
     * <pre>
     * The FRN security. Must have frn_details populated on the product_details oneof.
     * </pre>
     *
     * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.security.SecurityProto, fintekkers.models.security.SecurityProto.Builder, fintekkers.models.security.SecurityProtoOrBuilder> 
        getSecurityFieldBuilder() {
      if (securityBuilder_ == null) {
        securityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.security.SecurityProto, fintekkers.models.security.SecurityProto.Builder, fintekkers.models.security.SecurityProtoOrBuilder>(
                getSecurity(),
                getParentForChildren(),
                isClean());
        security_ = null;
      }
      return securityBuilder_;
    }

    private fintekkers.models.util.DecimalValue.DecimalValueProto cleanPrice_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> cleanPriceBuilder_;
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     * @return Whether the cleanPrice field is set.
     */
    public boolean hasCleanPrice() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     * @return The cleanPrice.
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto getCleanPrice() {
      if (cleanPriceBuilder_ == null) {
        return cleanPrice_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : cleanPrice_;
      } else {
        return cleanPriceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    public Builder setCleanPrice(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (cleanPriceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cleanPrice_ = value;
      } else {
        cleanPriceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    public Builder setCleanPrice(
        fintekkers.models.util.DecimalValue.DecimalValueProto.Builder builderForValue) {
      if (cleanPriceBuilder_ == null) {
        cleanPrice_ = builderForValue.build();
      } else {
        cleanPriceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    public Builder mergeCleanPrice(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (cleanPriceBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          cleanPrice_ != null &&
          cleanPrice_ != fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance()) {
          getCleanPriceBuilder().mergeFrom(value);
        } else {
          cleanPrice_ = value;
        }
      } else {
        cleanPriceBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    public Builder clearCleanPrice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cleanPrice_ = null;
      if (cleanPriceBuilder_ != null) {
        cleanPriceBuilder_.dispose();
        cleanPriceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto.Builder getCleanPriceBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCleanPriceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getCleanPriceOrBuilder() {
      if (cleanPriceBuilder_ != null) {
        return cleanPriceBuilder_.getMessageOrBuilder();
      } else {
        return cleanPrice_ == null ?
            fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : cleanPrice_;
      }
    }
    /**
     * <pre>
     * Market clean price as a percentage of face value (e.g. 99.75 = 99.75% of par).
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> 
        getCleanPriceFieldBuilder() {
      if (cleanPriceBuilder_ == null) {
        cleanPriceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder>(
                getCleanPrice(),
                getParentForChildren(),
                isClean());
        cleanPrice_ = null;
      }
      return cleanPriceBuilder_;
    }

    private fintekkers.requests.valuation.YieldCurveInput curve_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.YieldCurveInput, fintekkers.requests.valuation.YieldCurveInput.Builder, fintekkers.requests.valuation.YieldCurveInputOrBuilder> curveBuilder_;
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     * @return Whether the curve field is set.
     */
    public boolean hasCurve() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     * @return The curve.
     */
    public fintekkers.requests.valuation.YieldCurveInput getCurve() {
      if (curveBuilder_ == null) {
        return curve_ == null ? fintekkers.requests.valuation.YieldCurveInput.getDefaultInstance() : curve_;
      } else {
        return curveBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    public Builder setCurve(fintekkers.requests.valuation.YieldCurveInput value) {
      if (curveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        curve_ = value;
      } else {
        curveBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    public Builder setCurve(
        fintekkers.requests.valuation.YieldCurveInput.Builder builderForValue) {
      if (curveBuilder_ == null) {
        curve_ = builderForValue.build();
      } else {
        curveBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    public Builder mergeCurve(fintekkers.requests.valuation.YieldCurveInput value) {
      if (curveBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          curve_ != null &&
          curve_ != fintekkers.requests.valuation.YieldCurveInput.getDefaultInstance()) {
          getCurveBuilder().mergeFrom(value);
        } else {
          curve_ = value;
        }
      } else {
        curveBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    public Builder clearCurve() {
      bitField0_ = (bitField0_ & ~0x00000004);
      curve_ = null;
      if (curveBuilder_ != null) {
        curveBuilder_.dispose();
        curveBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    public fintekkers.requests.valuation.YieldCurveInput.Builder getCurveBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCurveFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    public fintekkers.requests.valuation.YieldCurveInputOrBuilder getCurveOrBuilder() {
      if (curveBuilder_ != null) {
        return curveBuilder_.getMessageOrBuilder();
      } else {
        return curve_ == null ?
            fintekkers.requests.valuation.YieldCurveInput.getDefaultInstance() : curve_;
      }
    }
    /**
     * <pre>
     * Yield curve for projecting floating coupons and discounting cashflows.
     * curve.index must match security.frn_details.reference_rate_index.
     * A single curve is used for both projection and discounting (single-curve framework).
     * This is appropriate for RFR-based FRNs (SOFR, SONIA, ESTR, TONA).
     * </pre>
     *
     * <code>.fintekkers.requests.valuation.YieldCurveInput curve = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.YieldCurveInput, fintekkers.requests.valuation.YieldCurveInput.Builder, fintekkers.requests.valuation.YieldCurveInputOrBuilder> 
        getCurveFieldBuilder() {
      if (curveBuilder_ == null) {
        curveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.valuation.YieldCurveInput, fintekkers.requests.valuation.YieldCurveInput.Builder, fintekkers.requests.valuation.YieldCurveInputOrBuilder>(
                getCurve(),
                getParentForChildren(),
                isClean());
        curve_ = null;
      }
      return curveBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.requests.valuation.FrnInput)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.requests.valuation.FrnInput)
  private static final fintekkers.requests.valuation.FrnInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.requests.valuation.FrnInput();
  }

  public static fintekkers.requests.valuation.FrnInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FrnInput>
      PARSER = new com.google.protobuf.AbstractParser<FrnInput>() {
    @java.lang.Override
    public FrnInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FrnInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FrnInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.requests.valuation.FrnInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

