// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/valuation/product_inputs.proto

package fintekkers.requests.valuation;

/**
 * <pre>
 * ═══════════════════════════════════════════════════════════════════════════
 * ProductInput — the dispatch field on ValuationRequestProto.
 * Exactly one variant should be set per request. The service routes to the
 * appropriate calculation engine based on which oneof field is populated.
 * Field numbers are reserved per the platform product roadmap:
 *   1–7  fixed-income (bond, callable, tips, muni, amortizing, ...)
 *   8    frn
 *   9–12 rates/credit (swap, xccy, repo, loan)
 *   13+  other (mbs, money market, futures, scenario, krd, ...)
 * ═══════════════════════════════════════════════════════════════════════════
 * </pre>
 *
 * Protobuf type {@code fintekkers.requests.valuation.ProductInput}
 */
public final class ProductInput extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.requests.valuation.ProductInput)
    ProductInputOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductInput.newBuilder() to construct.
  private ProductInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductInput() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductInput();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_ProductInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_ProductInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.requests.valuation.ProductInput.class, fintekkers.requests.valuation.ProductInput.Builder.class);
  }

  private int inputCase_ = 0;
  private java.lang.Object input_;
  public enum InputCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BOND(1),
    TIPS(2),
    FRN(8),
    INPUT_NOT_SET(0);
    private final int value;
    private InputCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InputCase valueOf(int value) {
      return forNumber(value);
    }

    public static InputCase forNumber(int value) {
      switch (value) {
        case 1: return BOND;
        case 2: return TIPS;
        case 8: return FRN;
        case 0: return INPUT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public InputCase
  getInputCase() {
    return InputCase.forNumber(
        inputCase_);
  }

  public static final int BOND_FIELD_NUMBER = 1;
  /**
   * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
   * @return Whether the bond field is set.
   */
  @java.lang.Override
  public boolean hasBond() {
    return inputCase_ == 1;
  }
  /**
   * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
   * @return The bond.
   */
  @java.lang.Override
  public fintekkers.requests.valuation.BondInput getBond() {
    if (inputCase_ == 1) {
       return (fintekkers.requests.valuation.BondInput) input_;
    }
    return fintekkers.requests.valuation.BondInput.getDefaultInstance();
  }
  /**
   * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
   */
  @java.lang.Override
  public fintekkers.requests.valuation.BondInputOrBuilder getBondOrBuilder() {
    if (inputCase_ == 1) {
       return (fintekkers.requests.valuation.BondInput) input_;
    }
    return fintekkers.requests.valuation.BondInput.getDefaultInstance();
  }

  public static final int TIPS_FIELD_NUMBER = 2;
  /**
   * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
   * @return Whether the tips field is set.
   */
  @java.lang.Override
  public boolean hasTips() {
    return inputCase_ == 2;
  }
  /**
   * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
   * @return The tips.
   */
  @java.lang.Override
  public fintekkers.requests.valuation.TipsInput getTips() {
    if (inputCase_ == 2) {
       return (fintekkers.requests.valuation.TipsInput) input_;
    }
    return fintekkers.requests.valuation.TipsInput.getDefaultInstance();
  }
  /**
   * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
   */
  @java.lang.Override
  public fintekkers.requests.valuation.TipsInputOrBuilder getTipsOrBuilder() {
    if (inputCase_ == 2) {
       return (fintekkers.requests.valuation.TipsInput) input_;
    }
    return fintekkers.requests.valuation.TipsInput.getDefaultInstance();
  }

  public static final int FRN_FIELD_NUMBER = 8;
  /**
   * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
   * @return Whether the frn field is set.
   */
  @java.lang.Override
  public boolean hasFrn() {
    return inputCase_ == 8;
  }
  /**
   * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
   * @return The frn.
   */
  @java.lang.Override
  public fintekkers.requests.valuation.FrnInput getFrn() {
    if (inputCase_ == 8) {
       return (fintekkers.requests.valuation.FrnInput) input_;
    }
    return fintekkers.requests.valuation.FrnInput.getDefaultInstance();
  }
  /**
   * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
   */
  @java.lang.Override
  public fintekkers.requests.valuation.FrnInputOrBuilder getFrnOrBuilder() {
    if (inputCase_ == 8) {
       return (fintekkers.requests.valuation.FrnInput) input_;
    }
    return fintekkers.requests.valuation.FrnInput.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (inputCase_ == 1) {
      output.writeMessage(1, (fintekkers.requests.valuation.BondInput) input_);
    }
    if (inputCase_ == 2) {
      output.writeMessage(2, (fintekkers.requests.valuation.TipsInput) input_);
    }
    if (inputCase_ == 8) {
      output.writeMessage(8, (fintekkers.requests.valuation.FrnInput) input_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (inputCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (fintekkers.requests.valuation.BondInput) input_);
    }
    if (inputCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (fintekkers.requests.valuation.TipsInput) input_);
    }
    if (inputCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (fintekkers.requests.valuation.FrnInput) input_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.requests.valuation.ProductInput)) {
      return super.equals(obj);
    }
    fintekkers.requests.valuation.ProductInput other = (fintekkers.requests.valuation.ProductInput) obj;

    if (!getInputCase().equals(other.getInputCase())) return false;
    switch (inputCase_) {
      case 1:
        if (!getBond()
            .equals(other.getBond())) return false;
        break;
      case 2:
        if (!getTips()
            .equals(other.getTips())) return false;
        break;
      case 8:
        if (!getFrn()
            .equals(other.getFrn())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (inputCase_) {
      case 1:
        hash = (37 * hash) + BOND_FIELD_NUMBER;
        hash = (53 * hash) + getBond().hashCode();
        break;
      case 2:
        hash = (37 * hash) + TIPS_FIELD_NUMBER;
        hash = (53 * hash) + getTips().hashCode();
        break;
      case 8:
        hash = (37 * hash) + FRN_FIELD_NUMBER;
        hash = (53 * hash) + getFrn().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.requests.valuation.ProductInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.valuation.ProductInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.requests.valuation.ProductInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.valuation.ProductInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.requests.valuation.ProductInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ═══════════════════════════════════════════════════════════════════════════
   * ProductInput — the dispatch field on ValuationRequestProto.
   * Exactly one variant should be set per request. The service routes to the
   * appropriate calculation engine based on which oneof field is populated.
   * Field numbers are reserved per the platform product roadmap:
   *   1–7  fixed-income (bond, callable, tips, muni, amortizing, ...)
   *   8    frn
   *   9–12 rates/credit (swap, xccy, repo, loan)
   *   13+  other (mbs, money market, futures, scenario, krd, ...)
   * ═══════════════════════════════════════════════════════════════════════════
   * </pre>
   *
   * Protobuf type {@code fintekkers.requests.valuation.ProductInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.requests.valuation.ProductInput)
      fintekkers.requests.valuation.ProductInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_ProductInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_ProductInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.requests.valuation.ProductInput.class, fintekkers.requests.valuation.ProductInput.Builder.class);
    }

    // Construct using fintekkers.requests.valuation.ProductInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bondBuilder_ != null) {
        bondBuilder_.clear();
      }
      if (tipsBuilder_ != null) {
        tipsBuilder_.clear();
      }
      if (frnBuilder_ != null) {
        frnBuilder_.clear();
      }
      inputCase_ = 0;
      input_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.requests.valuation.ProductInputProtos.internal_static_fintekkers_requests_valuation_ProductInput_descriptor;
    }

    @java.lang.Override
    public fintekkers.requests.valuation.ProductInput getDefaultInstanceForType() {
      return fintekkers.requests.valuation.ProductInput.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.requests.valuation.ProductInput build() {
      fintekkers.requests.valuation.ProductInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.requests.valuation.ProductInput buildPartial() {
      fintekkers.requests.valuation.ProductInput result = new fintekkers.requests.valuation.ProductInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(fintekkers.requests.valuation.ProductInput result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(fintekkers.requests.valuation.ProductInput result) {
      result.inputCase_ = inputCase_;
      result.input_ = this.input_;
      if (inputCase_ == 1 &&
          bondBuilder_ != null) {
        result.input_ = bondBuilder_.build();
      }
      if (inputCase_ == 2 &&
          tipsBuilder_ != null) {
        result.input_ = tipsBuilder_.build();
      }
      if (inputCase_ == 8 &&
          frnBuilder_ != null) {
        result.input_ = frnBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.requests.valuation.ProductInput) {
        return mergeFrom((fintekkers.requests.valuation.ProductInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.requests.valuation.ProductInput other) {
      if (other == fintekkers.requests.valuation.ProductInput.getDefaultInstance()) return this;
      switch (other.getInputCase()) {
        case BOND: {
          mergeBond(other.getBond());
          break;
        }
        case TIPS: {
          mergeTips(other.getTips());
          break;
        }
        case FRN: {
          mergeFrn(other.getFrn());
          break;
        }
        case INPUT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBondFieldBuilder().getBuilder(),
                  extensionRegistry);
              inputCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTipsFieldBuilder().getBuilder(),
                  extensionRegistry);
              inputCase_ = 2;
              break;
            } // case 18
            case 66: {
              input.readMessage(
                  getFrnFieldBuilder().getBuilder(),
                  extensionRegistry);
              inputCase_ = 8;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int inputCase_ = 0;
    private java.lang.Object input_;
    public InputCase
        getInputCase() {
      return InputCase.forNumber(
          inputCase_);
    }

    public Builder clearInput() {
      inputCase_ = 0;
      input_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.BondInput, fintekkers.requests.valuation.BondInput.Builder, fintekkers.requests.valuation.BondInputOrBuilder> bondBuilder_;
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     * @return Whether the bond field is set.
     */
    @java.lang.Override
    public boolean hasBond() {
      return inputCase_ == 1;
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     * @return The bond.
     */
    @java.lang.Override
    public fintekkers.requests.valuation.BondInput getBond() {
      if (bondBuilder_ == null) {
        if (inputCase_ == 1) {
          return (fintekkers.requests.valuation.BondInput) input_;
        }
        return fintekkers.requests.valuation.BondInput.getDefaultInstance();
      } else {
        if (inputCase_ == 1) {
          return bondBuilder_.getMessage();
        }
        return fintekkers.requests.valuation.BondInput.getDefaultInstance();
      }
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    public Builder setBond(fintekkers.requests.valuation.BondInput value) {
      if (bondBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
        onChanged();
      } else {
        bondBuilder_.setMessage(value);
      }
      inputCase_ = 1;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    public Builder setBond(
        fintekkers.requests.valuation.BondInput.Builder builderForValue) {
      if (bondBuilder_ == null) {
        input_ = builderForValue.build();
        onChanged();
      } else {
        bondBuilder_.setMessage(builderForValue.build());
      }
      inputCase_ = 1;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    public Builder mergeBond(fintekkers.requests.valuation.BondInput value) {
      if (bondBuilder_ == null) {
        if (inputCase_ == 1 &&
            input_ != fintekkers.requests.valuation.BondInput.getDefaultInstance()) {
          input_ = fintekkers.requests.valuation.BondInput.newBuilder((fintekkers.requests.valuation.BondInput) input_)
              .mergeFrom(value).buildPartial();
        } else {
          input_ = value;
        }
        onChanged();
      } else {
        if (inputCase_ == 1) {
          bondBuilder_.mergeFrom(value);
        } else {
          bondBuilder_.setMessage(value);
        }
      }
      inputCase_ = 1;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    public Builder clearBond() {
      if (bondBuilder_ == null) {
        if (inputCase_ == 1) {
          inputCase_ = 0;
          input_ = null;
          onChanged();
        }
      } else {
        if (inputCase_ == 1) {
          inputCase_ = 0;
          input_ = null;
        }
        bondBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    public fintekkers.requests.valuation.BondInput.Builder getBondBuilder() {
      return getBondFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    @java.lang.Override
    public fintekkers.requests.valuation.BondInputOrBuilder getBondOrBuilder() {
      if ((inputCase_ == 1) && (bondBuilder_ != null)) {
        return bondBuilder_.getMessageOrBuilder();
      } else {
        if (inputCase_ == 1) {
          return (fintekkers.requests.valuation.BondInput) input_;
        }
        return fintekkers.requests.valuation.BondInput.getDefaultInstance();
      }
    }
    /**
     * <code>.fintekkers.requests.valuation.BondInput bond = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.BondInput, fintekkers.requests.valuation.BondInput.Builder, fintekkers.requests.valuation.BondInputOrBuilder> 
        getBondFieldBuilder() {
      if (bondBuilder_ == null) {
        if (!(inputCase_ == 1)) {
          input_ = fintekkers.requests.valuation.BondInput.getDefaultInstance();
        }
        bondBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.valuation.BondInput, fintekkers.requests.valuation.BondInput.Builder, fintekkers.requests.valuation.BondInputOrBuilder>(
                (fintekkers.requests.valuation.BondInput) input_,
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      inputCase_ = 1;
      onChanged();
      return bondBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.TipsInput, fintekkers.requests.valuation.TipsInput.Builder, fintekkers.requests.valuation.TipsInputOrBuilder> tipsBuilder_;
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     * @return Whether the tips field is set.
     */
    @java.lang.Override
    public boolean hasTips() {
      return inputCase_ == 2;
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     * @return The tips.
     */
    @java.lang.Override
    public fintekkers.requests.valuation.TipsInput getTips() {
      if (tipsBuilder_ == null) {
        if (inputCase_ == 2) {
          return (fintekkers.requests.valuation.TipsInput) input_;
        }
        return fintekkers.requests.valuation.TipsInput.getDefaultInstance();
      } else {
        if (inputCase_ == 2) {
          return tipsBuilder_.getMessage();
        }
        return fintekkers.requests.valuation.TipsInput.getDefaultInstance();
      }
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    public Builder setTips(fintekkers.requests.valuation.TipsInput value) {
      if (tipsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
        onChanged();
      } else {
        tipsBuilder_.setMessage(value);
      }
      inputCase_ = 2;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    public Builder setTips(
        fintekkers.requests.valuation.TipsInput.Builder builderForValue) {
      if (tipsBuilder_ == null) {
        input_ = builderForValue.build();
        onChanged();
      } else {
        tipsBuilder_.setMessage(builderForValue.build());
      }
      inputCase_ = 2;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    public Builder mergeTips(fintekkers.requests.valuation.TipsInput value) {
      if (tipsBuilder_ == null) {
        if (inputCase_ == 2 &&
            input_ != fintekkers.requests.valuation.TipsInput.getDefaultInstance()) {
          input_ = fintekkers.requests.valuation.TipsInput.newBuilder((fintekkers.requests.valuation.TipsInput) input_)
              .mergeFrom(value).buildPartial();
        } else {
          input_ = value;
        }
        onChanged();
      } else {
        if (inputCase_ == 2) {
          tipsBuilder_.mergeFrom(value);
        } else {
          tipsBuilder_.setMessage(value);
        }
      }
      inputCase_ = 2;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    public Builder clearTips() {
      if (tipsBuilder_ == null) {
        if (inputCase_ == 2) {
          inputCase_ = 0;
          input_ = null;
          onChanged();
        }
      } else {
        if (inputCase_ == 2) {
          inputCase_ = 0;
          input_ = null;
        }
        tipsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    public fintekkers.requests.valuation.TipsInput.Builder getTipsBuilder() {
      return getTipsFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    @java.lang.Override
    public fintekkers.requests.valuation.TipsInputOrBuilder getTipsOrBuilder() {
      if ((inputCase_ == 2) && (tipsBuilder_ != null)) {
        return tipsBuilder_.getMessageOrBuilder();
      } else {
        if (inputCase_ == 2) {
          return (fintekkers.requests.valuation.TipsInput) input_;
        }
        return fintekkers.requests.valuation.TipsInput.getDefaultInstance();
      }
    }
    /**
     * <code>.fintekkers.requests.valuation.TipsInput tips = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.TipsInput, fintekkers.requests.valuation.TipsInput.Builder, fintekkers.requests.valuation.TipsInputOrBuilder> 
        getTipsFieldBuilder() {
      if (tipsBuilder_ == null) {
        if (!(inputCase_ == 2)) {
          input_ = fintekkers.requests.valuation.TipsInput.getDefaultInstance();
        }
        tipsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.valuation.TipsInput, fintekkers.requests.valuation.TipsInput.Builder, fintekkers.requests.valuation.TipsInputOrBuilder>(
                (fintekkers.requests.valuation.TipsInput) input_,
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      inputCase_ = 2;
      onChanged();
      return tipsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.FrnInput, fintekkers.requests.valuation.FrnInput.Builder, fintekkers.requests.valuation.FrnInputOrBuilder> frnBuilder_;
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     * @return Whether the frn field is set.
     */
    @java.lang.Override
    public boolean hasFrn() {
      return inputCase_ == 8;
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     * @return The frn.
     */
    @java.lang.Override
    public fintekkers.requests.valuation.FrnInput getFrn() {
      if (frnBuilder_ == null) {
        if (inputCase_ == 8) {
          return (fintekkers.requests.valuation.FrnInput) input_;
        }
        return fintekkers.requests.valuation.FrnInput.getDefaultInstance();
      } else {
        if (inputCase_ == 8) {
          return frnBuilder_.getMessage();
        }
        return fintekkers.requests.valuation.FrnInput.getDefaultInstance();
      }
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    public Builder setFrn(fintekkers.requests.valuation.FrnInput value) {
      if (frnBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
        onChanged();
      } else {
        frnBuilder_.setMessage(value);
      }
      inputCase_ = 8;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    public Builder setFrn(
        fintekkers.requests.valuation.FrnInput.Builder builderForValue) {
      if (frnBuilder_ == null) {
        input_ = builderForValue.build();
        onChanged();
      } else {
        frnBuilder_.setMessage(builderForValue.build());
      }
      inputCase_ = 8;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    public Builder mergeFrn(fintekkers.requests.valuation.FrnInput value) {
      if (frnBuilder_ == null) {
        if (inputCase_ == 8 &&
            input_ != fintekkers.requests.valuation.FrnInput.getDefaultInstance()) {
          input_ = fintekkers.requests.valuation.FrnInput.newBuilder((fintekkers.requests.valuation.FrnInput) input_)
              .mergeFrom(value).buildPartial();
        } else {
          input_ = value;
        }
        onChanged();
      } else {
        if (inputCase_ == 8) {
          frnBuilder_.mergeFrom(value);
        } else {
          frnBuilder_.setMessage(value);
        }
      }
      inputCase_ = 8;
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    public Builder clearFrn() {
      if (frnBuilder_ == null) {
        if (inputCase_ == 8) {
          inputCase_ = 0;
          input_ = null;
          onChanged();
        }
      } else {
        if (inputCase_ == 8) {
          inputCase_ = 0;
          input_ = null;
        }
        frnBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    public fintekkers.requests.valuation.FrnInput.Builder getFrnBuilder() {
      return getFrnFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    @java.lang.Override
    public fintekkers.requests.valuation.FrnInputOrBuilder getFrnOrBuilder() {
      if ((inputCase_ == 8) && (frnBuilder_ != null)) {
        return frnBuilder_.getMessageOrBuilder();
      } else {
        if (inputCase_ == 8) {
          return (fintekkers.requests.valuation.FrnInput) input_;
        }
        return fintekkers.requests.valuation.FrnInput.getDefaultInstance();
      }
    }
    /**
     * <code>.fintekkers.requests.valuation.FrnInput frn = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.valuation.FrnInput, fintekkers.requests.valuation.FrnInput.Builder, fintekkers.requests.valuation.FrnInputOrBuilder> 
        getFrnFieldBuilder() {
      if (frnBuilder_ == null) {
        if (!(inputCase_ == 8)) {
          input_ = fintekkers.requests.valuation.FrnInput.getDefaultInstance();
        }
        frnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.valuation.FrnInput, fintekkers.requests.valuation.FrnInput.Builder, fintekkers.requests.valuation.FrnInputOrBuilder>(
                (fintekkers.requests.valuation.FrnInput) input_,
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      inputCase_ = 8;
      onChanged();
      return frnBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.requests.valuation.ProductInput)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.requests.valuation.ProductInput)
  private static final fintekkers.requests.valuation.ProductInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.requests.valuation.ProductInput();
  }

  public static fintekkers.requests.valuation.ProductInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductInput>
      PARSER = new com.google.protobuf.AbstractParser<ProductInput>() {
    @java.lang.Override
    public ProductInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProductInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.requests.valuation.ProductInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

