// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/valuation/product_inputs.proto

package fintekkers.requests.valuation;

public interface SecurityBasedCurveInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintekkers.requests.valuation.SecurityBasedCurveInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Which government benchmark this curve represents.
   * Must be one of the government curve identifiers: US_TREASURY, UK_GILT,
   * DE_BUND, JP_JGB.
   * </pre>
   *
   * <code>.fintekkers.models.security.index.IndexTypeProto index = 1;</code>
   * @return The enum numeric value on the wire for index.
   */
  int getIndexValue();
  /**
   * <pre>
   * Which government benchmark this curve represents.
   * Must be one of the government curve identifiers: US_TREASURY, UK_GILT,
   * DE_BUND, JP_JGB.
   * </pre>
   *
   * <code>.fintekkers.models.security.index.IndexTypeProto index = 1;</code>
   * @return The index.
   */
  fintekkers.models.security.index.IndexTypeProto getIndex();

  /**
   * <pre>
   * As-of date for the curve, typically today or the most recent business day.
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalDateProto reference_date = 2;</code>
   * @return Whether the referenceDate field is set.
   */
  boolean hasReferenceDate();
  /**
   * <pre>
   * As-of date for the curve, typically today or the most recent business day.
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalDateProto reference_date = 2;</code>
   * @return The referenceDate.
   */
  fintekkers.models.util.LocalDate.LocalDateProto getReferenceDate();
  /**
   * <pre>
   * As-of date for the curve, typically today or the most recent business day.
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalDateProto reference_date = 2;</code>
   */
  fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getReferenceDateOrBuilder();

  /**
   * <pre>
   * Benchmark securities sorted by maturity ascending. Each entry pairs a
   * security with its observed clean price. The engine processes them in order,
   * bootstrapping the zero rate at each maturity from the previously solved
   * shorter-dated zeros.
   * </pre>
   *
   * <code>repeated .fintekkers.requests.valuation.SecurityCurvePoint points = 3;</code>
   */
  java.util.List<fintekkers.requests.valuation.SecurityCurvePoint> 
      getPointsList();
  /**
   * <pre>
   * Benchmark securities sorted by maturity ascending. Each entry pairs a
   * security with its observed clean price. The engine processes them in order,
   * bootstrapping the zero rate at each maturity from the previously solved
   * shorter-dated zeros.
   * </pre>
   *
   * <code>repeated .fintekkers.requests.valuation.SecurityCurvePoint points = 3;</code>
   */
  fintekkers.requests.valuation.SecurityCurvePoint getPoints(int index);
  /**
   * <pre>
   * Benchmark securities sorted by maturity ascending. Each entry pairs a
   * security with its observed clean price. The engine processes them in order,
   * bootstrapping the zero rate at each maturity from the previously solved
   * shorter-dated zeros.
   * </pre>
   *
   * <code>repeated .fintekkers.requests.valuation.SecurityCurvePoint points = 3;</code>
   */
  int getPointsCount();
  /**
   * <pre>
   * Benchmark securities sorted by maturity ascending. Each entry pairs a
   * security with its observed clean price. The engine processes them in order,
   * bootstrapping the zero rate at each maturity from the previously solved
   * shorter-dated zeros.
   * </pre>
   *
   * <code>repeated .fintekkers.requests.valuation.SecurityCurvePoint points = 3;</code>
   */
  java.util.List<? extends fintekkers.requests.valuation.SecurityCurvePointOrBuilder> 
      getPointsOrBuilderList();
  /**
   * <pre>
   * Benchmark securities sorted by maturity ascending. Each entry pairs a
   * security with its observed clean price. The engine processes them in order,
   * bootstrapping the zero rate at each maturity from the previously solved
   * shorter-dated zeros.
   * </pre>
   *
   * <code>repeated .fintekkers.requests.valuation.SecurityCurvePoint points = 3;</code>
   */
  fintekkers.requests.valuation.SecurityCurvePointOrBuilder getPointsOrBuilder(
      int index);
}
