// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/valuation/product_inputs.proto

package fintekkers.requests.valuation;

public interface SecurityCurvePointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintekkers.requests.valuation.SecurityCurvePoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The benchmark bond (must have fixed coupon, maturity_date, coupon_frequency,
   * face_value, and coupon_rate populated).
   * </pre>
   *
   * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
   * @return Whether the security field is set.
   */
  boolean hasSecurity();
  /**
   * <pre>
   * The benchmark bond (must have fixed coupon, maturity_date, coupon_frequency,
   * face_value, and coupon_rate populated).
   * </pre>
   *
   * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
   * @return The security.
   */
  fintekkers.models.security.SecurityProto getSecurity();
  /**
   * <pre>
   * The benchmark bond (must have fixed coupon, maturity_date, coupon_frequency,
   * face_value, and coupon_rate populated).
   * </pre>
   *
   * <code>.fintekkers.models.security.SecurityProto security = 1;</code>
   */
  fintekkers.models.security.SecurityProtoOrBuilder getSecurityOrBuilder();

  /**
   * <pre>
   * Market clean price as a percentage of face value (e.g. 99.50 = 99.50% of par).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
   * @return Whether the cleanPrice field is set.
   */
  boolean hasCleanPrice();
  /**
   * <pre>
   * Market clean price as a percentage of face value (e.g. 99.50 = 99.50% of par).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
   * @return The cleanPrice.
   */
  fintekkers.models.util.DecimalValue.DecimalValueProto getCleanPrice();
  /**
   * <pre>
   * Market clean price as a percentage of face value (e.g. 99.50 = 99.50% of par).
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto clean_price = 2;</code>
   */
  fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getCleanPriceOrBuilder();
}
