// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/security/index/index_type.proto

package fintekkers.models.security.index;

/**
 * Protobuf enum {@code fintekkers.models.security.index.IndexTypeProto}
 */
public enum IndexTypeProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_INDEX_TYPE = 0;</code>
   */
  UNKNOWN_INDEX_TYPE(0),
  /**
   * <pre>
   *Consumer Price Index - All Urban Consumers
   * </pre>
   *
   * <code>CPI_U = 1;</code>
   */
  CPI_U(1),
  /**
   * <pre>
   *Consumer Price Index - Urban Wage Earners and Clerical Workers
   * </pre>
   *
   * <code>CPI_W = 2;</code>
   */
  CPI_W(2),
  /**
   * <pre>
   *CPI less food and energy
   * </pre>
   *
   * <code>CORE_CPI = 3;</code>
   */
  CORE_CPI(3),
  /**
   * <pre>
   *Personal Consumption Expenditures
   * </pre>
   *
   * <code>PCE = 4;</code>
   */
  PCE(4),
  /**
   * <pre>
   *Harmonised Index of Consumer Prices (EU)
   * </pre>
   *
   * <code>HICP = 5;</code>
   */
  HICP(5),
  /**
   * <pre>
   *Floating rate benchmarks
   * </pre>
   *
   * <code>SOFR = 10;</code>
   */
  SOFR(10),
  /**
   * <pre>
   *13-week Treasury bill auction high rate
   * </pre>
   *
   * <code>T_BILL_13_WEEK = 11;</code>
   */
  T_BILL_13_WEEK(11),
  /**
   * <pre>
   *Federal Funds effective rate
   * </pre>
   *
   * <code>FED_FUNDS = 12;</code>
   */
  FED_FUNDS(12),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_INDEX_TYPE = 0;</code>
   */
  public static final int UNKNOWN_INDEX_TYPE_VALUE = 0;
  /**
   * <pre>
   *Consumer Price Index - All Urban Consumers
   * </pre>
   *
   * <code>CPI_U = 1;</code>
   */
  public static final int CPI_U_VALUE = 1;
  /**
   * <pre>
   *Consumer Price Index - Urban Wage Earners and Clerical Workers
   * </pre>
   *
   * <code>CPI_W = 2;</code>
   */
  public static final int CPI_W_VALUE = 2;
  /**
   * <pre>
   *CPI less food and energy
   * </pre>
   *
   * <code>CORE_CPI = 3;</code>
   */
  public static final int CORE_CPI_VALUE = 3;
  /**
   * <pre>
   *Personal Consumption Expenditures
   * </pre>
   *
   * <code>PCE = 4;</code>
   */
  public static final int PCE_VALUE = 4;
  /**
   * <pre>
   *Harmonised Index of Consumer Prices (EU)
   * </pre>
   *
   * <code>HICP = 5;</code>
   */
  public static final int HICP_VALUE = 5;
  /**
   * <pre>
   *Floating rate benchmarks
   * </pre>
   *
   * <code>SOFR = 10;</code>
   */
  public static final int SOFR_VALUE = 10;
  /**
   * <pre>
   *13-week Treasury bill auction high rate
   * </pre>
   *
   * <code>T_BILL_13_WEEK = 11;</code>
   */
  public static final int T_BILL_13_WEEK_VALUE = 11;
  /**
   * <pre>
   *Federal Funds effective rate
   * </pre>
   *
   * <code>FED_FUNDS = 12;</code>
   */
  public static final int FED_FUNDS_VALUE = 12;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static IndexTypeProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static IndexTypeProto forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_INDEX_TYPE;
      case 1: return CPI_U;
      case 2: return CPI_W;
      case 3: return CORE_CPI;
      case 4: return PCE;
      case 5: return HICP;
      case 10: return SOFR;
      case 11: return T_BILL_13_WEEK;
      case 12: return FED_FUNDS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<IndexTypeProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      IndexTypeProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<IndexTypeProto>() {
          public IndexTypeProto findValueByNumber(int number) {
            return IndexTypeProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return fintekkers.models.security.index.IndexTypeProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final IndexTypeProto[] VALUES = values();

  public static IndexTypeProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private IndexTypeProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fintekkers.models.security.index.IndexTypeProto)
}

