// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/price/create_price_response.proto

package fintekkers.requests.price;

/**
 * Protobuf type {@code fintekkers.requests.price.CreatePriceResponseProto}
 */
public final class CreatePriceResponseProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.requests.price.CreatePriceResponseProto)
    CreatePriceResponseProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreatePriceResponseProto.newBuilder() to construct.
  private CreatePriceResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreatePriceResponseProto() {
    objectClass_ = "";
    version_ = "";
    priceResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreatePriceResponseProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.requests.price.CreatePriceResponseProtos.internal_static_fintekkers_requests_price_CreatePriceResponseProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.requests.price.CreatePriceResponseProtos.internal_static_fintekkers_requests_price_CreatePriceResponseProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.requests.price.CreatePriceResponseProto.class, fintekkers.requests.price.CreatePriceResponseProto.Builder.class);
  }

  public static final int OBJECT_CLASS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectClass_ = "";
  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  @java.lang.Override
  public java.lang.String getObjectClass() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectClass_ = s;
      return s;
    }
  }
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectClassBytes() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATE_PRICE_REQUEST_FIELD_NUMBER = 20;
  private fintekkers.requests.price.CreatePriceRequestProto createPriceRequest_;
  /**
   * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
   * @return Whether the createPriceRequest field is set.
   */
  @java.lang.Override
  public boolean hasCreatePriceRequest() {
    return createPriceRequest_ != null;
  }
  /**
   * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
   * @return The createPriceRequest.
   */
  @java.lang.Override
  public fintekkers.requests.price.CreatePriceRequestProto getCreatePriceRequest() {
    return createPriceRequest_ == null ? fintekkers.requests.price.CreatePriceRequestProto.getDefaultInstance() : createPriceRequest_;
  }
  /**
   * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
   */
  @java.lang.Override
  public fintekkers.requests.price.CreatePriceRequestProtoOrBuilder getCreatePriceRequestOrBuilder() {
    return createPriceRequest_ == null ? fintekkers.requests.price.CreatePriceRequestProto.getDefaultInstance() : createPriceRequest_;
  }

  public static final int PRICE_RESPONSE_FIELD_NUMBER = 30;
  @SuppressWarnings("serial")
  private java.util.List<fintekkers.models.price.PriceProto> priceResponse_;
  /**
   * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
   */
  @java.lang.Override
  public java.util.List<fintekkers.models.price.PriceProto> getPriceResponseList() {
    return priceResponse_;
  }
  /**
   * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
   */
  @java.lang.Override
  public java.util.List<? extends fintekkers.models.price.PriceProtoOrBuilder> 
      getPriceResponseOrBuilderList() {
    return priceResponse_;
  }
  /**
   * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
   */
  @java.lang.Override
  public int getPriceResponseCount() {
    return priceResponse_.size();
  }
  /**
   * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
   */
  @java.lang.Override
  public fintekkers.models.price.PriceProto getPriceResponse(int index) {
    return priceResponse_.get(index);
  }
  /**
   * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
   */
  @java.lang.Override
  public fintekkers.models.price.PriceProtoOrBuilder getPriceResponseOrBuilder(
      int index) {
    return priceResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectClass_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectClass_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (createPriceRequest_ != null) {
      output.writeMessage(20, getCreatePriceRequest());
    }
    for (int i = 0; i < priceResponse_.size(); i++) {
      output.writeMessage(30, priceResponse_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectClass_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectClass_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (createPriceRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getCreatePriceRequest());
    }
    for (int i = 0; i < priceResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(30, priceResponse_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.requests.price.CreatePriceResponseProto)) {
      return super.equals(obj);
    }
    fintekkers.requests.price.CreatePriceResponseProto other = (fintekkers.requests.price.CreatePriceResponseProto) obj;

    if (!getObjectClass()
        .equals(other.getObjectClass())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasCreatePriceRequest() != other.hasCreatePriceRequest()) return false;
    if (hasCreatePriceRequest()) {
      if (!getCreatePriceRequest()
          .equals(other.getCreatePriceRequest())) return false;
    }
    if (!getPriceResponseList()
        .equals(other.getPriceResponseList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getObjectClass().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasCreatePriceRequest()) {
      hash = (37 * hash) + CREATE_PRICE_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getCreatePriceRequest().hashCode();
    }
    if (getPriceResponseCount() > 0) {
      hash = (37 * hash) + PRICE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getPriceResponseList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.requests.price.CreatePriceResponseProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.requests.price.CreatePriceResponseProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fintekkers.requests.price.CreatePriceResponseProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.requests.price.CreatePriceResponseProto)
      fintekkers.requests.price.CreatePriceResponseProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.requests.price.CreatePriceResponseProtos.internal_static_fintekkers_requests_price_CreatePriceResponseProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.requests.price.CreatePriceResponseProtos.internal_static_fintekkers_requests_price_CreatePriceResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.requests.price.CreatePriceResponseProto.class, fintekkers.requests.price.CreatePriceResponseProto.Builder.class);
    }

    // Construct using fintekkers.requests.price.CreatePriceResponseProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      objectClass_ = "";
      version_ = "";
      createPriceRequest_ = null;
      if (createPriceRequestBuilder_ != null) {
        createPriceRequestBuilder_.dispose();
        createPriceRequestBuilder_ = null;
      }
      if (priceResponseBuilder_ == null) {
        priceResponse_ = java.util.Collections.emptyList();
      } else {
        priceResponse_ = null;
        priceResponseBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.requests.price.CreatePriceResponseProtos.internal_static_fintekkers_requests_price_CreatePriceResponseProto_descriptor;
    }

    @java.lang.Override
    public fintekkers.requests.price.CreatePriceResponseProto getDefaultInstanceForType() {
      return fintekkers.requests.price.CreatePriceResponseProto.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.requests.price.CreatePriceResponseProto build() {
      fintekkers.requests.price.CreatePriceResponseProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.requests.price.CreatePriceResponseProto buildPartial() {
      fintekkers.requests.price.CreatePriceResponseProto result = new fintekkers.requests.price.CreatePriceResponseProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(fintekkers.requests.price.CreatePriceResponseProto result) {
      if (priceResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          priceResponse_ = java.util.Collections.unmodifiableList(priceResponse_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.priceResponse_ = priceResponse_;
      } else {
        result.priceResponse_ = priceResponseBuilder_.build();
      }
    }

    private void buildPartial0(fintekkers.requests.price.CreatePriceResponseProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.objectClass_ = objectClass_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.createPriceRequest_ = createPriceRequestBuilder_ == null
            ? createPriceRequest_
            : createPriceRequestBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.requests.price.CreatePriceResponseProto) {
        return mergeFrom((fintekkers.requests.price.CreatePriceResponseProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.requests.price.CreatePriceResponseProto other) {
      if (other == fintekkers.requests.price.CreatePriceResponseProto.getDefaultInstance()) return this;
      if (!other.getObjectClass().isEmpty()) {
        objectClass_ = other.objectClass_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasCreatePriceRequest()) {
        mergeCreatePriceRequest(other.getCreatePriceRequest());
      }
      if (priceResponseBuilder_ == null) {
        if (!other.priceResponse_.isEmpty()) {
          if (priceResponse_.isEmpty()) {
            priceResponse_ = other.priceResponse_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePriceResponseIsMutable();
            priceResponse_.addAll(other.priceResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.priceResponse_.isEmpty()) {
          if (priceResponseBuilder_.isEmpty()) {
            priceResponseBuilder_.dispose();
            priceResponseBuilder_ = null;
            priceResponse_ = other.priceResponse_;
            bitField0_ = (bitField0_ & ~0x00000008);
            priceResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPriceResponseFieldBuilder() : null;
          } else {
            priceResponseBuilder_.addAllMessages(other.priceResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              objectClass_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 162: {
              input.readMessage(
                  getCreatePriceRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 162
            case 242: {
              fintekkers.models.price.PriceProto m =
                  input.readMessage(
                      fintekkers.models.price.PriceProto.parser(),
                      extensionRegistry);
              if (priceResponseBuilder_ == null) {
                ensurePriceResponseIsMutable();
                priceResponse_.add(m);
              } else {
                priceResponseBuilder_.addMessage(m);
              }
              break;
            } // case 242
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object objectClass_ = "";
    /**
     * <code>string object_class = 1;</code>
     * @return The objectClass.
     */
    public java.lang.String getObjectClass() {
      java.lang.Object ref = objectClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @return The bytes for objectClass.
     */
    public com.google.protobuf.ByteString
        getObjectClassBytes() {
      java.lang.Object ref = objectClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClass(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectClass_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectClass() {
      objectClass_ = getDefaultInstance().getObjectClass();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The bytes for objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectClass_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private fintekkers.requests.price.CreatePriceRequestProto createPriceRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.price.CreatePriceRequestProto, fintekkers.requests.price.CreatePriceRequestProto.Builder, fintekkers.requests.price.CreatePriceRequestProtoOrBuilder> createPriceRequestBuilder_;
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     * @return Whether the createPriceRequest field is set.
     */
    public boolean hasCreatePriceRequest() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     * @return The createPriceRequest.
     */
    public fintekkers.requests.price.CreatePriceRequestProto getCreatePriceRequest() {
      if (createPriceRequestBuilder_ == null) {
        return createPriceRequest_ == null ? fintekkers.requests.price.CreatePriceRequestProto.getDefaultInstance() : createPriceRequest_;
      } else {
        return createPriceRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    public Builder setCreatePriceRequest(fintekkers.requests.price.CreatePriceRequestProto value) {
      if (createPriceRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createPriceRequest_ = value;
      } else {
        createPriceRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    public Builder setCreatePriceRequest(
        fintekkers.requests.price.CreatePriceRequestProto.Builder builderForValue) {
      if (createPriceRequestBuilder_ == null) {
        createPriceRequest_ = builderForValue.build();
      } else {
        createPriceRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    public Builder mergeCreatePriceRequest(fintekkers.requests.price.CreatePriceRequestProto value) {
      if (createPriceRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          createPriceRequest_ != null &&
          createPriceRequest_ != fintekkers.requests.price.CreatePriceRequestProto.getDefaultInstance()) {
          getCreatePriceRequestBuilder().mergeFrom(value);
        } else {
          createPriceRequest_ = value;
        }
      } else {
        createPriceRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    public Builder clearCreatePriceRequest() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createPriceRequest_ = null;
      if (createPriceRequestBuilder_ != null) {
        createPriceRequestBuilder_.dispose();
        createPriceRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    public fintekkers.requests.price.CreatePriceRequestProto.Builder getCreatePriceRequestBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCreatePriceRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    public fintekkers.requests.price.CreatePriceRequestProtoOrBuilder getCreatePriceRequestOrBuilder() {
      if (createPriceRequestBuilder_ != null) {
        return createPriceRequestBuilder_.getMessageOrBuilder();
      } else {
        return createPriceRequest_ == null ?
            fintekkers.requests.price.CreatePriceRequestProto.getDefaultInstance() : createPriceRequest_;
      }
    }
    /**
     * <code>.fintekkers.requests.price.CreatePriceRequestProto create_price_request = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.requests.price.CreatePriceRequestProto, fintekkers.requests.price.CreatePriceRequestProto.Builder, fintekkers.requests.price.CreatePriceRequestProtoOrBuilder> 
        getCreatePriceRequestFieldBuilder() {
      if (createPriceRequestBuilder_ == null) {
        createPriceRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.requests.price.CreatePriceRequestProto, fintekkers.requests.price.CreatePriceRequestProto.Builder, fintekkers.requests.price.CreatePriceRequestProtoOrBuilder>(
                getCreatePriceRequest(),
                getParentForChildren(),
                isClean());
        createPriceRequest_ = null;
      }
      return createPriceRequestBuilder_;
    }

    private java.util.List<fintekkers.models.price.PriceProto> priceResponse_ =
      java.util.Collections.emptyList();
    private void ensurePriceResponseIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        priceResponse_ = new java.util.ArrayList<fintekkers.models.price.PriceProto>(priceResponse_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        fintekkers.models.price.PriceProto, fintekkers.models.price.PriceProto.Builder, fintekkers.models.price.PriceProtoOrBuilder> priceResponseBuilder_;

    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public java.util.List<fintekkers.models.price.PriceProto> getPriceResponseList() {
      if (priceResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(priceResponse_);
      } else {
        return priceResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public int getPriceResponseCount() {
      if (priceResponseBuilder_ == null) {
        return priceResponse_.size();
      } else {
        return priceResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public fintekkers.models.price.PriceProto getPriceResponse(int index) {
      if (priceResponseBuilder_ == null) {
        return priceResponse_.get(index);
      } else {
        return priceResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder setPriceResponse(
        int index, fintekkers.models.price.PriceProto value) {
      if (priceResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceResponseIsMutable();
        priceResponse_.set(index, value);
        onChanged();
      } else {
        priceResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder setPriceResponse(
        int index, fintekkers.models.price.PriceProto.Builder builderForValue) {
      if (priceResponseBuilder_ == null) {
        ensurePriceResponseIsMutable();
        priceResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        priceResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder addPriceResponse(fintekkers.models.price.PriceProto value) {
      if (priceResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceResponseIsMutable();
        priceResponse_.add(value);
        onChanged();
      } else {
        priceResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder addPriceResponse(
        int index, fintekkers.models.price.PriceProto value) {
      if (priceResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceResponseIsMutable();
        priceResponse_.add(index, value);
        onChanged();
      } else {
        priceResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder addPriceResponse(
        fintekkers.models.price.PriceProto.Builder builderForValue) {
      if (priceResponseBuilder_ == null) {
        ensurePriceResponseIsMutable();
        priceResponse_.add(builderForValue.build());
        onChanged();
      } else {
        priceResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder addPriceResponse(
        int index, fintekkers.models.price.PriceProto.Builder builderForValue) {
      if (priceResponseBuilder_ == null) {
        ensurePriceResponseIsMutable();
        priceResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        priceResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder addAllPriceResponse(
        java.lang.Iterable<? extends fintekkers.models.price.PriceProto> values) {
      if (priceResponseBuilder_ == null) {
        ensurePriceResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, priceResponse_);
        onChanged();
      } else {
        priceResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder clearPriceResponse() {
      if (priceResponseBuilder_ == null) {
        priceResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        priceResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public Builder removePriceResponse(int index) {
      if (priceResponseBuilder_ == null) {
        ensurePriceResponseIsMutable();
        priceResponse_.remove(index);
        onChanged();
      } else {
        priceResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public fintekkers.models.price.PriceProto.Builder getPriceResponseBuilder(
        int index) {
      return getPriceResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public fintekkers.models.price.PriceProtoOrBuilder getPriceResponseOrBuilder(
        int index) {
      if (priceResponseBuilder_ == null) {
        return priceResponse_.get(index);  } else {
        return priceResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public java.util.List<? extends fintekkers.models.price.PriceProtoOrBuilder> 
         getPriceResponseOrBuilderList() {
      if (priceResponseBuilder_ != null) {
        return priceResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(priceResponse_);
      }
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public fintekkers.models.price.PriceProto.Builder addPriceResponseBuilder() {
      return getPriceResponseFieldBuilder().addBuilder(
          fintekkers.models.price.PriceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public fintekkers.models.price.PriceProto.Builder addPriceResponseBuilder(
        int index) {
      return getPriceResponseFieldBuilder().addBuilder(
          index, fintekkers.models.price.PriceProto.getDefaultInstance());
    }
    /**
     * <code>repeated .fintekkers.models.price.PriceProto price_response = 30;</code>
     */
    public java.util.List<fintekkers.models.price.PriceProto.Builder> 
         getPriceResponseBuilderList() {
      return getPriceResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        fintekkers.models.price.PriceProto, fintekkers.models.price.PriceProto.Builder, fintekkers.models.price.PriceProtoOrBuilder> 
        getPriceResponseFieldBuilder() {
      if (priceResponseBuilder_ == null) {
        priceResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            fintekkers.models.price.PriceProto, fintekkers.models.price.PriceProto.Builder, fintekkers.models.price.PriceProtoOrBuilder>(
                priceResponse_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        priceResponse_ = null;
      }
      return priceResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.requests.price.CreatePriceResponseProto)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.requests.price.CreatePriceResponseProto)
  private static final fintekkers.requests.price.CreatePriceResponseProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.requests.price.CreatePriceResponseProto();
  }

  public static fintekkers.requests.price.CreatePriceResponseProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreatePriceResponseProto>
      PARSER = new com.google.protobuf.AbstractParser<CreatePriceResponseProto>() {
    @java.lang.Override
    public CreatePriceResponseProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreatePriceResponseProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreatePriceResponseProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.requests.price.CreatePriceResponseProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

