// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/services/transaction-service/transaction_service.proto

package fintekkers.services.transaction_service;

public final class TransactionService {
  private TransactionService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf service {@code fintekkers.services.transaction_service.Transaction}
   */
  public static abstract class Transaction
      implements com.google.protobuf.Service {
    protected Transaction() {}

    public interface Interface {
      /**
       * <code>rpc CreateOrUpdate(.fintekkers.requests.transaction.CreateTransactionRequestProto) returns (.fintekkers.requests.transaction.CreateTransactionResponseProto);</code>
       */
      public abstract void createOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.CreateTransactionResponseProto> done);

      /**
       * <code>rpc GetByIds(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (.fintekkers.requests.transaction.QueryTransactionResponseProto);</code>
       */
      public abstract void getByIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done);

      /**
       * <code>rpc Search(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (stream .fintekkers.requests.transaction.QueryTransactionResponseProto);</code>
       */
      public abstract void search(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done);

      /**
       * <code>rpc ListIds(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (.fintekkers.requests.transaction.QueryTransactionResponseProto);</code>
       */
      public abstract void listIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done);

      /**
       * <code>rpc Delete(.fintekkers.requests.util.DeleteRequestProto) returns (.fintekkers.requests.util.DeleteResponseProto);</code>
       */
      public abstract void delete(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.util.DeleteRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.util.DeleteResponseProto> done);

      /**
       * <code>rpc ValidateCreateOrUpdate(.fintekkers.requests.transaction.CreateTransactionRequestProto) returns (.fintekkers.requests.util.errors.SummaryProto);</code>
       */
      public abstract void validateCreateOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done);

      /**
       * <code>rpc ValidateQueryRequest(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (.fintekkers.requests.util.errors.SummaryProto);</code>
       */
      public abstract void validateQueryRequest(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done);

      /**
       * <code>rpc GetFields(.google.protobuf.Empty) returns (.fintekkers.requests.security.GetFieldValuesResponseProto);</code>
       */
      public abstract void getFields(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request,
          com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done);

      /**
       * <code>rpc GetFieldValues(.fintekkers.requests.security.GetFieldValuesRequestProto) returns (.fintekkers.requests.security.GetFieldValuesResponseProto);</code>
       */
      public abstract void getFieldValues(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.security.GetFieldValuesRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Transaction() {
        @java.lang.Override
        public  void createOrUpdate(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.transaction.CreateTransactionRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.transaction.CreateTransactionResponseProto> done) {
          impl.createOrUpdate(controller, request, done);
        }

        @java.lang.Override
        public  void getByIds(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.transaction.QueryTransactionRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done) {
          impl.getByIds(controller, request, done);
        }

        @java.lang.Override
        public  void search(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.transaction.QueryTransactionRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done) {
          impl.search(controller, request, done);
        }

        @java.lang.Override
        public  void listIds(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.transaction.QueryTransactionRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done) {
          impl.listIds(controller, request, done);
        }

        @java.lang.Override
        public  void delete(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.util.DeleteRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.util.DeleteResponseProto> done) {
          impl.delete(controller, request, done);
        }

        @java.lang.Override
        public  void validateCreateOrUpdate(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.transaction.CreateTransactionRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done) {
          impl.validateCreateOrUpdate(controller, request, done);
        }

        @java.lang.Override
        public  void validateQueryRequest(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.transaction.QueryTransactionRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done) {
          impl.validateQueryRequest(controller, request, done);
        }

        @java.lang.Override
        public  void getFields(
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Empty request,
            com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done) {
          impl.getFields(controller, request, done);
        }

        @java.lang.Override
        public  void getFieldValues(
            com.google.protobuf.RpcController controller,
            fintekkers.requests.security.GetFieldValuesRequestProto request,
            com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done) {
          impl.getFieldValues(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.createOrUpdate(controller, (fintekkers.requests.transaction.CreateTransactionRequestProto)request);
            case 1:
              return impl.getByIds(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request);
            case 2:
              return impl.search(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request);
            case 3:
              return impl.listIds(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request);
            case 4:
              return impl.delete(controller, (fintekkers.requests.util.DeleteRequestProto)request);
            case 5:
              return impl.validateCreateOrUpdate(controller, (fintekkers.requests.transaction.CreateTransactionRequestProto)request);
            case 6:
              return impl.validateQueryRequest(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request);
            case 7:
              return impl.getFields(controller, (com.google.protobuf.Empty)request);
            case 8:
              return impl.getFieldValues(controller, (fintekkers.requests.security.GetFieldValuesRequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return fintekkers.requests.transaction.CreateTransactionRequestProto.getDefaultInstance();
            case 1:
              return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
            case 2:
              return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
            case 3:
              return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
            case 4:
              return fintekkers.requests.util.DeleteRequestProto.getDefaultInstance();
            case 5:
              return fintekkers.requests.transaction.CreateTransactionRequestProto.getDefaultInstance();
            case 6:
              return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
            case 7:
              return com.google.protobuf.Empty.getDefaultInstance();
            case 8:
              return fintekkers.requests.security.GetFieldValuesRequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return fintekkers.requests.transaction.CreateTransactionResponseProto.getDefaultInstance();
            case 1:
              return fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance();
            case 2:
              return fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance();
            case 3:
              return fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance();
            case 4:
              return fintekkers.requests.util.DeleteResponseProto.getDefaultInstance();
            case 5:
              return fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance();
            case 6:
              return fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance();
            case 7:
              return fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance();
            case 8:
              return fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc CreateOrUpdate(.fintekkers.requests.transaction.CreateTransactionRequestProto) returns (.fintekkers.requests.transaction.CreateTransactionResponseProto);</code>
     */
    public abstract void createOrUpdate(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.transaction.CreateTransactionRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.transaction.CreateTransactionResponseProto> done);

    /**
     * <code>rpc GetByIds(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (.fintekkers.requests.transaction.QueryTransactionResponseProto);</code>
     */
    public abstract void getByIds(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.transaction.QueryTransactionRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done);

    /**
     * <code>rpc Search(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (stream .fintekkers.requests.transaction.QueryTransactionResponseProto);</code>
     */
    public abstract void search(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.transaction.QueryTransactionRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done);

    /**
     * <code>rpc ListIds(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (.fintekkers.requests.transaction.QueryTransactionResponseProto);</code>
     */
    public abstract void listIds(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.transaction.QueryTransactionRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done);

    /**
     * <code>rpc Delete(.fintekkers.requests.util.DeleteRequestProto) returns (.fintekkers.requests.util.DeleteResponseProto);</code>
     */
    public abstract void delete(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.util.DeleteRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.util.DeleteResponseProto> done);

    /**
     * <code>rpc ValidateCreateOrUpdate(.fintekkers.requests.transaction.CreateTransactionRequestProto) returns (.fintekkers.requests.util.errors.SummaryProto);</code>
     */
    public abstract void validateCreateOrUpdate(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.transaction.CreateTransactionRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done);

    /**
     * <code>rpc ValidateQueryRequest(.fintekkers.requests.transaction.QueryTransactionRequestProto) returns (.fintekkers.requests.util.errors.SummaryProto);</code>
     */
    public abstract void validateQueryRequest(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.transaction.QueryTransactionRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done);

    /**
     * <code>rpc GetFields(.google.protobuf.Empty) returns (.fintekkers.requests.security.GetFieldValuesResponseProto);</code>
     */
    public abstract void getFields(
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Empty request,
        com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done);

    /**
     * <code>rpc GetFieldValues(.fintekkers.requests.security.GetFieldValuesRequestProto) returns (.fintekkers.requests.security.GetFieldValuesResponseProto);</code>
     */
    public abstract void getFieldValues(
        com.google.protobuf.RpcController controller,
        fintekkers.requests.security.GetFieldValuesRequestProto request,
        com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return fintekkers.services.transaction_service.TransactionService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.createOrUpdate(controller, (fintekkers.requests.transaction.CreateTransactionRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.transaction.CreateTransactionResponseProto>specializeCallback(
              done));
          return;
        case 1:
          this.getByIds(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.transaction.QueryTransactionResponseProto>specializeCallback(
              done));
          return;
        case 2:
          this.search(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.transaction.QueryTransactionResponseProto>specializeCallback(
              done));
          return;
        case 3:
          this.listIds(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.transaction.QueryTransactionResponseProto>specializeCallback(
              done));
          return;
        case 4:
          this.delete(controller, (fintekkers.requests.util.DeleteRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.util.DeleteResponseProto>specializeCallback(
              done));
          return;
        case 5:
          this.validateCreateOrUpdate(controller, (fintekkers.requests.transaction.CreateTransactionRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.util.errors.Summary.SummaryProto>specializeCallback(
              done));
          return;
        case 6:
          this.validateQueryRequest(controller, (fintekkers.requests.transaction.QueryTransactionRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.util.errors.Summary.SummaryProto>specializeCallback(
              done));
          return;
        case 7:
          this.getFields(controller, (com.google.protobuf.Empty)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.security.GetFieldValuesResponseProto>specializeCallback(
              done));
          return;
        case 8:
          this.getFieldValues(controller, (fintekkers.requests.security.GetFieldValuesRequestProto)request,
            com.google.protobuf.RpcUtil.<fintekkers.requests.security.GetFieldValuesResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return fintekkers.requests.transaction.CreateTransactionRequestProto.getDefaultInstance();
        case 1:
          return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
        case 2:
          return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
        case 3:
          return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
        case 4:
          return fintekkers.requests.util.DeleteRequestProto.getDefaultInstance();
        case 5:
          return fintekkers.requests.transaction.CreateTransactionRequestProto.getDefaultInstance();
        case 6:
          return fintekkers.requests.transaction.QueryTransactionRequestProto.getDefaultInstance();
        case 7:
          return com.google.protobuf.Empty.getDefaultInstance();
        case 8:
          return fintekkers.requests.security.GetFieldValuesRequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return fintekkers.requests.transaction.CreateTransactionResponseProto.getDefaultInstance();
        case 1:
          return fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance();
        case 2:
          return fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance();
        case 3:
          return fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance();
        case 4:
          return fintekkers.requests.util.DeleteResponseProto.getDefaultInstance();
        case 5:
          return fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance();
        case 6:
          return fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance();
        case 7:
          return fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance();
        case 8:
          return fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends fintekkers.services.transaction_service.TransactionService.Transaction implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void createOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.CreateTransactionResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          fintekkers.requests.transaction.CreateTransactionResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.transaction.CreateTransactionResponseProto.class,
            fintekkers.requests.transaction.CreateTransactionResponseProto.getDefaultInstance()));
      }

      public  void getByIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.transaction.QueryTransactionResponseProto.class,
            fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance()));
      }

      public  void search(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.transaction.QueryTransactionResponseProto.class,
            fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance()));
      }

      public  void listIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.transaction.QueryTransactionResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.transaction.QueryTransactionResponseProto.class,
            fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance()));
      }

      public  void delete(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.util.DeleteRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.util.DeleteResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          fintekkers.requests.util.DeleteResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.util.DeleteResponseProto.class,
            fintekkers.requests.util.DeleteResponseProto.getDefaultInstance()));
      }

      public  void validateCreateOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.util.errors.Summary.SummaryProto.class,
            fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance()));
      }

      public  void validateQueryRequest(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.util.errors.Summary.SummaryProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(6),
          controller,
          request,
          fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.util.errors.Summary.SummaryProto.class,
            fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance()));
      }

      public  void getFields(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request,
          com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(7),
          controller,
          request,
          fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.security.GetFieldValuesResponseProto.class,
            fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance()));
      }

      public  void getFieldValues(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.security.GetFieldValuesRequestProto request,
          com.google.protobuf.RpcCallback<fintekkers.requests.security.GetFieldValuesResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(8),
          controller,
          request,
          fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            fintekkers.requests.security.GetFieldValuesResponseProto.class,
            fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public fintekkers.requests.transaction.CreateTransactionResponseProto createOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.transaction.QueryTransactionResponseProto getByIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.transaction.QueryTransactionResponseProto search(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.transaction.QueryTransactionResponseProto listIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.util.DeleteResponseProto delete(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.util.DeleteRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.util.errors.Summary.SummaryProto validateCreateOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.util.errors.Summary.SummaryProto validateQueryRequest(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.security.GetFieldValuesResponseProto getFields(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request)
          throws com.google.protobuf.ServiceException;

      public fintekkers.requests.security.GetFieldValuesResponseProto getFieldValues(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.security.GetFieldValuesRequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public fintekkers.requests.transaction.CreateTransactionResponseProto createOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.transaction.CreateTransactionResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          fintekkers.requests.transaction.CreateTransactionResponseProto.getDefaultInstance());
      }


      public fintekkers.requests.transaction.QueryTransactionResponseProto getByIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.transaction.QueryTransactionResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance());
      }


      public fintekkers.requests.transaction.QueryTransactionResponseProto search(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.transaction.QueryTransactionResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance());
      }


      public fintekkers.requests.transaction.QueryTransactionResponseProto listIds(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.transaction.QueryTransactionResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          fintekkers.requests.transaction.QueryTransactionResponseProto.getDefaultInstance());
      }


      public fintekkers.requests.util.DeleteResponseProto delete(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.util.DeleteRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.util.DeleteResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          fintekkers.requests.util.DeleteResponseProto.getDefaultInstance());
      }


      public fintekkers.requests.util.errors.Summary.SummaryProto validateCreateOrUpdate(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.CreateTransactionRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.util.errors.Summary.SummaryProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance());
      }


      public fintekkers.requests.util.errors.Summary.SummaryProto validateQueryRequest(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.transaction.QueryTransactionRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.util.errors.Summary.SummaryProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(6),
          controller,
          request,
          fintekkers.requests.util.errors.Summary.SummaryProto.getDefaultInstance());
      }


      public fintekkers.requests.security.GetFieldValuesResponseProto getFields(
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Empty request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.security.GetFieldValuesResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(7),
          controller,
          request,
          fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance());
      }


      public fintekkers.requests.security.GetFieldValuesResponseProto getFieldValues(
          com.google.protobuf.RpcController controller,
          fintekkers.requests.security.GetFieldValuesRequestProto request)
          throws com.google.protobuf.ServiceException {
        return (fintekkers.requests.security.GetFieldValuesResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(8),
          controller,
          request,
          fintekkers.requests.security.GetFieldValuesResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:fintekkers.services.transaction_service.Transaction)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nAfintekkers/services/transaction-servic" +
      "e/transaction_service.proto\022\'fintekkers." +
      "services.transaction_service\032@fintekkers" +
      "/requests/transaction/create_transaction" +
      "_request.proto\032Afintekkers/requests/tran" +
      "saction/create_transaction_response.prot" +
      "o\032?fintekkers/requests/transaction/query" +
      "_transaction_request.proto\032@fintekkers/r" +
      "equests/transaction/query_transaction_re" +
      "sponse.proto\032-fintekkers/requests/util/e" +
      "rrors/summary.proto\032-fintekkers/requests" +
      "/util/delete_request.proto\032;fintekkers/r" +
      "equests/security/get_field_values_reques" +
      "t.proto\032<fintekkers/requests/security/ge" +
      "t_field_values_response.proto\032\033google/pr" +
      "otobuf/empty.proto2\244\t\n\013Transaction\022\221\001\n\016C" +
      "reateOrUpdate\022>.fintekkers.requests.tran" +
      "saction.CreateTransactionRequestProto\032?." +
      "fintekkers.requests.transaction.CreateTr" +
      "ansactionResponseProto\022\211\001\n\010GetByIds\022=.fi" +
      "ntekkers.requests.transaction.QueryTrans" +
      "actionRequestProto\032>.fintekkers.requests" +
      ".transaction.QueryTransactionResponsePro" +
      "to\022\211\001\n\006Search\022=.fintekkers.requests.tran" +
      "saction.QueryTransactionRequestProto\032>.f" +
      "intekkers.requests.transaction.QueryTran" +
      "sactionResponseProto0\001\022\210\001\n\007ListIds\022=.fin" +
      "tekkers.requests.transaction.QueryTransa" +
      "ctionRequestProto\032>.fintekkers.requests." +
      "transaction.QueryTransactionResponseProt" +
      "o\022e\n\006Delete\022,.fintekkers.requests.util.D" +
      "eleteRequestProto\032-.fintekkers.requests." +
      "util.DeleteResponseProto\022\207\001\n\026ValidateCre" +
      "ateOrUpdate\022>.fintekkers.requests.transa" +
      "ction.CreateTransactionRequestProto\032-.fi" +
      "ntekkers.requests.util.errors.SummaryPro" +
      "to\022\204\001\n\024ValidateQueryRequest\022=.fintekkers" +
      ".requests.transaction.QueryTransactionRe" +
      "questProto\032-.fintekkers.requests.util.er" +
      "rors.SummaryProto\022^\n\tGetFields\022\026.google." +
      "protobuf.Empty\0329.fintekkers.requests.sec" +
      "urity.GetFieldValuesResponseProto\022\205\001\n\016Ge" +
      "tFieldValues\0228.fintekkers.requests.secur" +
      "ity.GetFieldValuesRequestProto\0329.fintekk" +
      "ers.requests.security.GetFieldValuesResp" +
      "onseProtoB\006\210\001\001\220\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fintekkers.requests.transaction.CreateTransactionRequestProtos.getDescriptor(),
          fintekkers.requests.transaction.CreateTransactionResponseProtos.getDescriptor(),
          fintekkers.requests.transaction.QueryTransactionRequestProtos.getDescriptor(),
          fintekkers.requests.transaction.QueryTransactionResponseProtos.getDescriptor(),
          fintekkers.requests.util.errors.Summary.getDescriptor(),
          fintekkers.requests.util.DeleteRequestProtos.getDescriptor(),
          fintekkers.requests.security.GetFieldValuesRequestProtos.getDescriptor(),
          fintekkers.requests.security.GetFieldValuesResponseProtos.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    fintekkers.requests.transaction.CreateTransactionRequestProtos.getDescriptor();
    fintekkers.requests.transaction.CreateTransactionResponseProtos.getDescriptor();
    fintekkers.requests.transaction.QueryTransactionRequestProtos.getDescriptor();
    fintekkers.requests.transaction.QueryTransactionResponseProtos.getDescriptor();
    fintekkers.requests.util.errors.Summary.getDescriptor();
    fintekkers.requests.util.DeleteRequestProtos.getDescriptor();
    fintekkers.requests.security.GetFieldValuesRequestProtos.getDescriptor();
    fintekkers.requests.security.GetFieldValuesResponseProtos.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
