// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/security/security.proto

package fintekkers.models.security;

/**
 * <pre>
 * Cash security details.
 * </pre>
 *
 * Protobuf type {@code fintekkers.models.security.CashDetailsProto}
 */
public final class CashDetailsProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.models.security.CashDetailsProto)
    CashDetailsProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CashDetailsProto.newBuilder() to construct.
  private CashDetailsProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CashDetailsProto() {
    cashId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CashDetailsProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_CashDetailsProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_CashDetailsProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.models.security.CashDetailsProto.class, fintekkers.models.security.CashDetailsProto.Builder.class);
  }

  public static final int CASH_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cashId_ = "";
  /**
   * <pre>
   *e.g. "USD", "EUR", "GBP"
   * </pre>
   *
   * <code>string cash_id = 1;</code>
   * @return The cashId.
   */
  @java.lang.Override
  public java.lang.String getCashId() {
    java.lang.Object ref = cashId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cashId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *e.g. "USD", "EUR", "GBP"
   * </pre>
   *
   * <code>string cash_id = 1;</code>
   * @return The bytes for cashId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCashIdBytes() {
    java.lang.Object ref = cashId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cashId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cashId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cashId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cashId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cashId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.models.security.CashDetailsProto)) {
      return super.equals(obj);
    }
    fintekkers.models.security.CashDetailsProto other = (fintekkers.models.security.CashDetailsProto) obj;

    if (!getCashId()
        .equals(other.getCashId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CASH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCashId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.models.security.CashDetailsProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.security.CashDetailsProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.CashDetailsProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.CashDetailsProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.models.security.CashDetailsProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Cash security details.
   * </pre>
   *
   * Protobuf type {@code fintekkers.models.security.CashDetailsProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.models.security.CashDetailsProto)
      fintekkers.models.security.CashDetailsProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_CashDetailsProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_CashDetailsProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.models.security.CashDetailsProto.class, fintekkers.models.security.CashDetailsProto.Builder.class);
    }

    // Construct using fintekkers.models.security.CashDetailsProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cashId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_CashDetailsProto_descriptor;
    }

    @java.lang.Override
    public fintekkers.models.security.CashDetailsProto getDefaultInstanceForType() {
      return fintekkers.models.security.CashDetailsProto.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.models.security.CashDetailsProto build() {
      fintekkers.models.security.CashDetailsProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.models.security.CashDetailsProto buildPartial() {
      fintekkers.models.security.CashDetailsProto result = new fintekkers.models.security.CashDetailsProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fintekkers.models.security.CashDetailsProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cashId_ = cashId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.models.security.CashDetailsProto) {
        return mergeFrom((fintekkers.models.security.CashDetailsProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.models.security.CashDetailsProto other) {
      if (other == fintekkers.models.security.CashDetailsProto.getDefaultInstance()) return this;
      if (!other.getCashId().isEmpty()) {
        cashId_ = other.cashId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cashId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object cashId_ = "";
    /**
     * <pre>
     *e.g. "USD", "EUR", "GBP"
     * </pre>
     *
     * <code>string cash_id = 1;</code>
     * @return The cashId.
     */
    public java.lang.String getCashId() {
      java.lang.Object ref = cashId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cashId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *e.g. "USD", "EUR", "GBP"
     * </pre>
     *
     * <code>string cash_id = 1;</code>
     * @return The bytes for cashId.
     */
    public com.google.protobuf.ByteString
        getCashIdBytes() {
      java.lang.Object ref = cashId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cashId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *e.g. "USD", "EUR", "GBP"
     * </pre>
     *
     * <code>string cash_id = 1;</code>
     * @param value The cashId to set.
     * @return This builder for chaining.
     */
    public Builder setCashId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cashId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *e.g. "USD", "EUR", "GBP"
     * </pre>
     *
     * <code>string cash_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCashId() {
      cashId_ = getDefaultInstance().getCashId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *e.g. "USD", "EUR", "GBP"
     * </pre>
     *
     * <code>string cash_id = 1;</code>
     * @param value The bytes for cashId to set.
     * @return This builder for chaining.
     */
    public Builder setCashIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cashId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.models.security.CashDetailsProto)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.models.security.CashDetailsProto)
  private static final fintekkers.models.security.CashDetailsProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.models.security.CashDetailsProto();
  }

  public static fintekkers.models.security.CashDetailsProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CashDetailsProto>
      PARSER = new com.google.protobuf.AbstractParser<CashDetailsProto>() {
    @java.lang.Override
    public CashDetailsProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CashDetailsProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CashDetailsProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.models.security.CashDetailsProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

