// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/security/security.proto

package fintekkers.models.security;

public final class SecurityProtos {
  private SecurityProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_SecurityProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_SecurityProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_BondDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_BondDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_TipsExtensionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_TipsExtensionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_FrnExtensionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_FrnExtensionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_IndexDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_IndexDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_EquityDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_EquityDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_CashDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_CashDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_FxSpotDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_FxSpotDetailsProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)fintekkers/models/security/security.pr" +
      "oto\022\032fintekkers.models.security\032*fintekk" +
      "ers/models/util/decimal_value.proto\032\'fin" +
      "tekkers/models/util/local_date.proto\032,fi" +
      "ntekkers/models/util/local_timestamp.pro" +
      "to\032!fintekkers/models/util/uuid.proto\0326f" +
      "intekkers/models/security/identifier/ide" +
      "ntifier.proto\032.fintekkers/models/securit" +
      "y/bond/issuance.proto\032-fintekkers/models" +
      "/security/product_type.proto\0320fintekkers" +
      "/models/security/instrument_type.proto\0327" +
      "fintekkers/models/security/security_quan" +
      "tity_type.proto\0321fintekkers/models/secur" +
      "ity/coupon_frequency.proto\032,fintekkers/m" +
      "odels/security/coupon_type.proto\0321fintek" +
      "kers/models/security/index/index_type.pr" +
      "oto\"\343\n\n\rSecurityProto\022\024\n\014object_class\030\001 " +
      "\001(\t\022\017\n\007version\030\002 \001(\t\022/\n\004uuid\030\005 \001(\0132!.fin" +
      "tekkers.models.util.UUIDProto\022:\n\005as_of\030\006" +
      " \001(\0132+.fintekkers.models.util.LocalTimes" +
      "tampProto\022\017\n\007is_link\030\007 \001(\010\022?\n\nvalid_from" +
      "\030\010 \001(\0132+.fintekkers.models.util.LocalTim" +
      "estampProto\022=\n\010valid_to\030\t \001(\0132+.fintekke" +
      "rs.models.util.LocalTimestampProto\022B\n\014pr" +
      "oduct_type\030\n \001(\0162,.fintekkers.models.sec" +
      "urity.ProductTypeProto\022H\n\017instrument_typ" +
      "e\030\020 \001(\0162/.fintekkers.models.security.Ins" +
      "trumentTypeProto\0227\n\004legs\030\021 \003(\0132).fintekk" +
      "ers.models.security.SecurityProto\022?\n\ndel" +
      "eted_at\030\017 \001(\0132+.fintekkers.models.util.L" +
      "ocalTimestampProto\022\023\n\013asset_class\030\013 \001(\t\022" +
      "\023\n\013issuer_name\030\014 \001(\t\022F\n\023settlement_curre" +
      "ncy\030\r \001(\0132).fintekkers.models.security.S" +
      "ecurityProto\022L\n\rquantity_type\030\016 \001(\01625.fi" +
      "ntekkers.models.security.SecurityQuantit" +
      "yTypeProto\022\023\n\013description\030) \001(\t\022@\n\013ident" +
      "ifiers\030* \003(\0132+.fintekkers.models.securit" +
      "y.IdentifierProto\022C\n\014bond_details\030\310\001 \001(\013" +
      "2,.fintekkers.models.security.BondDetail" +
      "sProto\022G\n\016tips_extension\030\311\001 \001(\0132..fintek" +
      "kers.models.security.TipsExtensionProto\022" +
      "E\n\rfrn_extension\030\312\001 \001(\0132-.fintekkers.mod" +
      "els.security.FrnExtensionProto\022G\n\rindex_" +
      "details\030\313\001 \001(\0132-.fintekkers.models.secur" +
      "ity.IndexDetailsProtoH\000\022I\n\016equity_detail" +
      "s\030\314\001 \001(\0132..fintekkers.models.security.Eq" +
      "uityDetailsProtoH\000\022E\n\014cash_details\030\315\001 \001(" +
      "\0132,.fintekkers.models.security.CashDetai" +
      "lsProtoH\000\022J\n\017fx_spot_details\030\316\001 \001(\0132..fi" +
      "ntekkers.models.security.FxSpotDetailsPr" +
      "otoH\000B\022\n\020non_bond_details\"\235\004\n\020BondDetail" +
      "sProto\022>\n\013coupon_rate\030\001 \001(\0132).fintekkers" +
      ".models.util.DecimalValueProto\022@\n\013coupon" +
      "_type\030\002 \001(\0162+.fintekkers.models.security" +
      ".CouponTypeProto\022J\n\020coupon_frequency\030\003 \001" +
      "(\01620.fintekkers.models.security.CouponFr" +
      "equencyProto\022:\n\ndated_date\030\004 \001(\0132&.finte" +
      "kkers.models.util.LocalDateProto\022=\n\nface" +
      "_value\030\005 \001(\0132).fintekkers.models.util.De" +
      "cimalValueProto\022:\n\nissue_date\030\006 \001(\0132&.fi" +
      "ntekkers.models.util.LocalDateProto\022=\n\rm" +
      "aturity_date\030\007 \001(\0132&.fintekkers.models.u" +
      "til.LocalDateProto\022E\n\rissuance_info\030\010 \003(" +
      "\0132..fintekkers.models.security.bond.Issu" +
      "anceProto\"\335\001\n\022TipsExtensionProto\022;\n\010base" +
      "_cpi\030\001 \001(\0132).fintekkers.models.util.Deci" +
      "malValueProto\022:\n\nindex_date\030\002 \001(\0132&.fint" +
      "ekkers.models.util.LocalDateProto\022N\n\024inf" +
      "lation_index_type\030\003 \001(\01620.fintekkers.mod" +
      "els.security.index.IndexTypeProto\"\351\001\n\021Fr" +
      "nExtensionProto\0229\n\006spread\030\001 \001(\0132).fintek" +
      "kers.models.util.DecimalValueProto\022N\n\024re" +
      "ference_rate_index\030\002 \001(\01620.fintekkers.mo" +
      "dels.security.index.IndexTypeProto\022I\n\017re" +
      "set_frequency\030\003 \001(\01620.fintekkers.models." +
      "security.CouponFrequencyProto\"\232\001\n\021IndexD" +
      "etailsProto\022D\n\nindex_type\030\001 \001(\01620.fintek" +
      "kers.models.security.index.IndexTypeProt" +
      "o\022?\n\014constituents\030\002 \003(\0132).fintekkers.mod" +
      "els.security.SecurityProto\"\024\n\022EquityDeta" +
      "ilsProto\"#\n\020CashDetailsProto\022\017\n\007cash_id\030" +
      "\001 \001(\t\"\255\001\n\022FxSpotDetailsProto\022@\n\rbase_cur" +
      "rency\030\001 \001(\0132).fintekkers.models.security" +
      ".SecurityProto\022A\n\016quote_currency\030\002 \001(\0132)" +
      ".fintekkers.models.security.SecurityProt" +
      "o\022\022\n\nconvention\030\003 \001(\tB\022B\016SecurityProtosP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fintekkers.models.util.DecimalValue.getDescriptor(),
          fintekkers.models.util.LocalDate.getDescriptor(),
          fintekkers.models.util.LocalTimestamp.getDescriptor(),
          fintekkers.models.util.Uuid.getDescriptor(),
          fintekkers.models.security.IdentifierProtos.getDescriptor(),
          fintekkers.models.security.bond.IssuanceProtos.getDescriptor(),
          fintekkers.models.security.ProductTypeProtos.getDescriptor(),
          fintekkers.models.security.InstrumentTypeProtos.getDescriptor(),
          fintekkers.models.security.SecurityQuantityTypeProtos.getDescriptor(),
          fintekkers.models.security.CouponFrequencyProtos.getDescriptor(),
          fintekkers.models.security.CouponTypeProtos.getDescriptor(),
          fintekkers.models.security.index.IndexTypeProtos.getDescriptor(),
        });
    internal_static_fintekkers_models_security_SecurityProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fintekkers_models_security_SecurityProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_SecurityProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "Uuid", "AsOf", "IsLink", "ValidFrom", "ValidTo", "ProductType", "InstrumentType", "Legs", "DeletedAt", "AssetClass", "IssuerName", "SettlementCurrency", "QuantityType", "Description", "Identifiers", "BondDetails", "TipsExtension", "FrnExtension", "IndexDetails", "EquityDetails", "CashDetails", "FxSpotDetails", "NonBondDetails", });
    internal_static_fintekkers_models_security_BondDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fintekkers_models_security_BondDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_BondDetailsProto_descriptor,
        new java.lang.String[] { "CouponRate", "CouponType", "CouponFrequency", "DatedDate", "FaceValue", "IssueDate", "MaturityDate", "IssuanceInfo", });
    internal_static_fintekkers_models_security_TipsExtensionProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fintekkers_models_security_TipsExtensionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_TipsExtensionProto_descriptor,
        new java.lang.String[] { "BaseCpi", "IndexDate", "InflationIndexType", });
    internal_static_fintekkers_models_security_FrnExtensionProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fintekkers_models_security_FrnExtensionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_FrnExtensionProto_descriptor,
        new java.lang.String[] { "Spread", "ReferenceRateIndex", "ResetFrequency", });
    internal_static_fintekkers_models_security_IndexDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_fintekkers_models_security_IndexDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_IndexDetailsProto_descriptor,
        new java.lang.String[] { "IndexType", "Constituents", });
    internal_static_fintekkers_models_security_EquityDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_fintekkers_models_security_EquityDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_EquityDetailsProto_descriptor,
        new java.lang.String[] { });
    internal_static_fintekkers_models_security_CashDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_fintekkers_models_security_CashDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_CashDetailsProto_descriptor,
        new java.lang.String[] { "CashId", });
    internal_static_fintekkers_models_security_FxSpotDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_fintekkers_models_security_FxSpotDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_FxSpotDetailsProto_descriptor,
        new java.lang.String[] { "BaseCurrency", "QuoteCurrency", "Convention", });
    fintekkers.models.util.DecimalValue.getDescriptor();
    fintekkers.models.util.LocalDate.getDescriptor();
    fintekkers.models.util.LocalTimestamp.getDescriptor();
    fintekkers.models.util.Uuid.getDescriptor();
    fintekkers.models.security.IdentifierProtos.getDescriptor();
    fintekkers.models.security.bond.IssuanceProtos.getDescriptor();
    fintekkers.models.security.ProductTypeProtos.getDescriptor();
    fintekkers.models.security.InstrumentTypeProtos.getDescriptor();
    fintekkers.models.security.SecurityQuantityTypeProtos.getDescriptor();
    fintekkers.models.security.CouponFrequencyProtos.getDescriptor();
    fintekkers.models.security.CouponTypeProtos.getDescriptor();
    fintekkers.models.security.index.IndexTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
