// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/security/security.proto

package fintekkers.models.security;

public final class SecurityProtos {
  private SecurityProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_SecurityProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_SecurityProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_BondDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_BondDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_TipsExtensionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_TipsExtensionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_FrnExtensionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_FrnExtensionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_IndexDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_IndexDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_EquityDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_EquityDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_CashDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_CashDetailsProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fintekkers_models_security_FxSpotDetailsProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fintekkers_models_security_FxSpotDetailsProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)fintekkers/models/security/security.pr" +
      "oto\022\032fintekkers.models.security\032*fintekk" +
      "ers/models/util/decimal_value.proto\032\'fin" +
      "tekkers/models/util/local_date.proto\032,fi" +
      "ntekkers/models/util/local_timestamp.pro" +
      "to\032!fintekkers/models/util/uuid.proto\0326f" +
      "intekkers/models/security/identifier/ide" +
      "ntifier.proto\032.fintekkers/models/securit" +
      "y/bond/issuance.proto\032-fintekkers/models" +
      "/security/product_type.proto\0320fintekkers" +
      "/models/security/instrument_type.proto\0327" +
      "fintekkers/models/security/security_quan" +
      "tity_type.proto\0321fintekkers/models/secur" +
      "ity/coupon_frequency.proto\032,fintekkers/m" +
      "odels/security/coupon_type.proto\0321fintek" +
      "kers/models/security/index/index_type.pr" +
      "oto\"\245\023\n\rSecurityProto\022\024\n\014object_class\030\001 " +
      "\001(\t\022\017\n\007version\030\002 \001(\t\022/\n\004uuid\030\005 \001(\0132!.fin" +
      "tekkers.models.util.UUIDProto\022:\n\005as_of\030\006" +
      " \001(\0132+.fintekkers.models.util.LocalTimes" +
      "tampProto\022\017\n\007is_link\030\007 \001(\010\022?\n\nvalid_from" +
      "\030\010 \001(\0132+.fintekkers.models.util.LocalTim" +
      "estampProto\022=\n\010valid_to\030\t \001(\0132+.fintekke" +
      "rs.models.util.LocalTimestampProto\022B\n\014pr" +
      "oduct_type\030\n \001(\0162,.fintekkers.models.sec" +
      "urity.ProductTypeProto\022H\n\017instrument_typ" +
      "e\030\020 \001(\0162/.fintekkers.models.security.Ins" +
      "trumentTypeProto\0227\n\004legs\030\021 \003(\0132).fintekk" +
      "ers.models.security.SecurityProto\022?\n\ndel" +
      "eted_at\030\017 \001(\0132+.fintekkers.models.util.L" +
      "ocalTimestampProto\022\023\n\013asset_class\030\013 \001(\t\022" +
      "\023\n\013issuer_name\030\014 \001(\t\022F\n\023settlement_curre" +
      "ncy\030\r \001(\0132).fintekkers.models.security.S" +
      "ecurityProto\022L\n\rquantity_type\030\016 \001(\01625.fi" +
      "ntekkers.models.security.SecurityQuantit" +
      "yTypeProto\022?\n\nidentifier\030( \001(\0132+.fintekk" +
      "ers.models.security.IdentifierProto\022\023\n\013d" +
      "escription\030) \001(\t\022@\n\013identifiers\030* \003(\0132+." +
      "fintekkers.models.security.IdentifierPro" +
      "to\022\017\n\007cash_id\0302 \001(\t\022>\n\013coupon_rate\030< \001(\013" +
      "2).fintekkers.models.util.DecimalValuePr" +
      "oto\022@\n\013coupon_type\030= \001(\0162+.fintekkers.mo" +
      "dels.security.CouponTypeProto\022J\n\020coupon_" +
      "frequency\030> \001(\01620.fintekkers.models.secu" +
      "rity.CouponFrequencyProto\022:\n\ndated_date\030" +
      "? \001(\0132&.fintekkers.models.util.LocalDate" +
      "Proto\022=\n\nface_value\030@ \001(\0132).fintekkers.m" +
      "odels.util.DecimalValueProto\022:\n\nissue_da" +
      "te\030A \001(\0132&.fintekkers.models.util.LocalD" +
      "ateProto\022=\n\rmaturity_date\030B \001(\0132&.fintek" +
      "kers.models.util.LocalDateProto\022E\n\rissua" +
      "nce_info\030C \003(\0132..fintekkers.models.secur" +
      "ity.bond.IssuanceProto\022;\n\010base_cpi\030F \001(\013" +
      "2).fintekkers.models.util.DecimalValuePr" +
      "oto\022:\n\nindex_date\030G \001(\0132&.fintekkers.mod" +
      "els.util.LocalDateProto\022N\n\024inflation_ind" +
      "ex_type\030H \001(\01620.fintekkers.models.securi" +
      "ty.index.IndexTypeProto\0229\n\006spread\030Z \001(\0132" +
      ").fintekkers.models.util.DecimalValuePro" +
      "to\022N\n\024reference_rate_index\030[ \001(\01620.finte" +
      "kkers.models.security.index.IndexTypePro" +
      "to\022I\n\017reset_frequency\030\\ \001(\01620.fintekkers" +
      ".models.security.CouponFrequencyProto\022D\n" +
      "\nindex_type\030P \001(\01620.fintekkers.models.se" +
      "curity.index.IndexTypeProto\022C\n\014bond_deta" +
      "ils\030\310\001 \001(\0132,.fintekkers.models.security." +
      "BondDetailsProto\022G\n\016tips_extension\030\311\001 \001(" +
      "\0132..fintekkers.models.security.TipsExten" +
      "sionProto\022E\n\rfrn_extension\030\312\001 \001(\0132-.fint" +
      "ekkers.models.security.FrnExtensionProto" +
      "\022G\n\rindex_details\030\313\001 \001(\0132-.fintekkers.mo" +
      "dels.security.IndexDetailsProtoH\000\022I\n\016equ" +
      "ity_details\030\314\001 \001(\0132..fintekkers.models.s" +
      "ecurity.EquityDetailsProtoH\000\022E\n\014cash_det" +
      "ails\030\315\001 \001(\0132,.fintekkers.models.security" +
      ".CashDetailsProtoH\000\022J\n\017fx_spot_details\030\316" +
      "\001 \001(\0132..fintekkers.models.security.FxSpo" +
      "tDetailsProtoH\000B\022\n\020non_bond_details\"\235\004\n\020" +
      "BondDetailsProto\022>\n\013coupon_rate\030\001 \001(\0132)." +
      "fintekkers.models.util.DecimalValueProto" +
      "\022@\n\013coupon_type\030\002 \001(\0162+.fintekkers.model" +
      "s.security.CouponTypeProto\022J\n\020coupon_fre" +
      "quency\030\003 \001(\01620.fintekkers.models.securit" +
      "y.CouponFrequencyProto\022:\n\ndated_date\030\004 \001" +
      "(\0132&.fintekkers.models.util.LocalDatePro" +
      "to\022=\n\nface_value\030\005 \001(\0132).fintekkers.mode" +
      "ls.util.DecimalValueProto\022:\n\nissue_date\030" +
      "\006 \001(\0132&.fintekkers.models.util.LocalDate" +
      "Proto\022=\n\rmaturity_date\030\007 \001(\0132&.fintekker" +
      "s.models.util.LocalDateProto\022E\n\rissuance" +
      "_info\030\010 \003(\0132..fintekkers.models.security" +
      ".bond.IssuanceProto\"\335\001\n\022TipsExtensionPro" +
      "to\022;\n\010base_cpi\030\001 \001(\0132).fintekkers.models" +
      ".util.DecimalValueProto\022:\n\nindex_date\030\002 " +
      "\001(\0132&.fintekkers.models.util.LocalDatePr" +
      "oto\022N\n\024inflation_index_type\030\003 \001(\01620.fint" +
      "ekkers.models.security.index.IndexTypePr" +
      "oto\"\351\001\n\021FrnExtensionProto\0229\n\006spread\030\001 \001(" +
      "\0132).fintekkers.models.util.DecimalValueP" +
      "roto\022N\n\024reference_rate_index\030\002 \001(\01620.fin" +
      "tekkers.models.security.index.IndexTypeP" +
      "roto\022I\n\017reset_frequency\030\003 \001(\01620.fintekke" +
      "rs.models.security.CouponFrequencyProto\"" +
      "\232\001\n\021IndexDetailsProto\022D\n\nindex_type\030\001 \001(" +
      "\01620.fintekkers.models.security.index.Ind" +
      "exTypeProto\022?\n\014constituents\030\002 \003(\0132).fint" +
      "ekkers.models.security.SecurityProto\"\024\n\022" +
      "EquityDetailsProto\"#\n\020CashDetailsProto\022\017" +
      "\n\007cash_id\030\001 \001(\t\"\255\001\n\022FxSpotDetailsProto\022@" +
      "\n\rbase_currency\030\001 \001(\0132).fintekkers.model" +
      "s.security.SecurityProto\022A\n\016quote_curren" +
      "cy\030\002 \001(\0132).fintekkers.models.security.Se" +
      "curityProto\022\022\n\nconvention\030\003 \001(\tB\022B\016Secur" +
      "ityProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          fintekkers.models.util.DecimalValue.getDescriptor(),
          fintekkers.models.util.LocalDate.getDescriptor(),
          fintekkers.models.util.LocalTimestamp.getDescriptor(),
          fintekkers.models.util.Uuid.getDescriptor(),
          fintekkers.models.security.IdentifierProtos.getDescriptor(),
          fintekkers.models.security.bond.IssuanceProtos.getDescriptor(),
          fintekkers.models.security.ProductTypeProtos.getDescriptor(),
          fintekkers.models.security.InstrumentTypeProtos.getDescriptor(),
          fintekkers.models.security.SecurityQuantityTypeProtos.getDescriptor(),
          fintekkers.models.security.CouponFrequencyProtos.getDescriptor(),
          fintekkers.models.security.CouponTypeProtos.getDescriptor(),
          fintekkers.models.security.index.IndexTypeProtos.getDescriptor(),
        });
    internal_static_fintekkers_models_security_SecurityProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fintekkers_models_security_SecurityProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_SecurityProto_descriptor,
        new java.lang.String[] { "ObjectClass", "Version", "Uuid", "AsOf", "IsLink", "ValidFrom", "ValidTo", "ProductType", "InstrumentType", "Legs", "DeletedAt", "AssetClass", "IssuerName", "SettlementCurrency", "QuantityType", "Identifier", "Description", "Identifiers", "CashId", "CouponRate", "CouponType", "CouponFrequency", "DatedDate", "FaceValue", "IssueDate", "MaturityDate", "IssuanceInfo", "BaseCpi", "IndexDate", "InflationIndexType", "Spread", "ReferenceRateIndex", "ResetFrequency", "IndexType", "BondDetails", "TipsExtension", "FrnExtension", "IndexDetails", "EquityDetails", "CashDetails", "FxSpotDetails", "NonBondDetails", });
    internal_static_fintekkers_models_security_BondDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fintekkers_models_security_BondDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_BondDetailsProto_descriptor,
        new java.lang.String[] { "CouponRate", "CouponType", "CouponFrequency", "DatedDate", "FaceValue", "IssueDate", "MaturityDate", "IssuanceInfo", });
    internal_static_fintekkers_models_security_TipsExtensionProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fintekkers_models_security_TipsExtensionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_TipsExtensionProto_descriptor,
        new java.lang.String[] { "BaseCpi", "IndexDate", "InflationIndexType", });
    internal_static_fintekkers_models_security_FrnExtensionProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fintekkers_models_security_FrnExtensionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_FrnExtensionProto_descriptor,
        new java.lang.String[] { "Spread", "ReferenceRateIndex", "ResetFrequency", });
    internal_static_fintekkers_models_security_IndexDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_fintekkers_models_security_IndexDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_IndexDetailsProto_descriptor,
        new java.lang.String[] { "IndexType", "Constituents", });
    internal_static_fintekkers_models_security_EquityDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_fintekkers_models_security_EquityDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_EquityDetailsProto_descriptor,
        new java.lang.String[] { });
    internal_static_fintekkers_models_security_CashDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_fintekkers_models_security_CashDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_CashDetailsProto_descriptor,
        new java.lang.String[] { "CashId", });
    internal_static_fintekkers_models_security_FxSpotDetailsProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_fintekkers_models_security_FxSpotDetailsProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fintekkers_models_security_FxSpotDetailsProto_descriptor,
        new java.lang.String[] { "BaseCurrency", "QuoteCurrency", "Convention", });
    fintekkers.models.util.DecimalValue.getDescriptor();
    fintekkers.models.util.LocalDate.getDescriptor();
    fintekkers.models.util.LocalTimestamp.getDescriptor();
    fintekkers.models.util.Uuid.getDescriptor();
    fintekkers.models.security.IdentifierProtos.getDescriptor();
    fintekkers.models.security.bond.IssuanceProtos.getDescriptor();
    fintekkers.models.security.ProductTypeProtos.getDescriptor();
    fintekkers.models.security.InstrumentTypeProtos.getDescriptor();
    fintekkers.models.security.SecurityQuantityTypeProtos.getDescriptor();
    fintekkers.models.security.CouponFrequencyProtos.getDescriptor();
    fintekkers.models.security.CouponTypeProtos.getDescriptor();
    fintekkers.models.security.index.IndexTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
