// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/security/security.proto

package fintekkers.models.security;

/**
 * <pre>
 * TIPS (Treasury Inflation-Protected Securities) extras.
 * Carries ONLY the TIPS-specific fields; shared bond fields live in
 * SecurityProto.bond_details. Populated when product_type == TIPS.
 * </pre>
 *
 * Protobuf type {@code fintekkers.models.security.TipsExtensionProto}
 */
public final class TipsExtensionProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.models.security.TipsExtensionProto)
    TipsExtensionProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TipsExtensionProto.newBuilder() to construct.
  private TipsExtensionProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TipsExtensionProto() {
    inflationIndexType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TipsExtensionProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_TipsExtensionProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_TipsExtensionProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.models.security.TipsExtensionProto.class, fintekkers.models.security.TipsExtensionProto.Builder.class);
  }

  public static final int BASE_CPI_FIELD_NUMBER = 1;
  private fintekkers.models.util.DecimalValue.DecimalValueProto baseCpi_;
  /**
   * <pre>
   *Reference CPI at bond issuance (e.g. 256.394)
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
   * @return Whether the baseCpi field is set.
   */
  @java.lang.Override
  public boolean hasBaseCpi() {
    return baseCpi_ != null;
  }
  /**
   * <pre>
   *Reference CPI at bond issuance (e.g. 256.394)
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
   * @return The baseCpi.
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProto getBaseCpi() {
    return baseCpi_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : baseCpi_;
  }
  /**
   * <pre>
   *Reference CPI at bond issuance (e.g. 256.394)
   * </pre>
   *
   * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getBaseCpiOrBuilder() {
    return baseCpi_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : baseCpi_;
  }

  public static final int INDEX_DATE_FIELD_NUMBER = 2;
  private fintekkers.models.util.LocalDate.LocalDateProto indexDate_;
  /**
   * <pre>
   *The date the base CPI was observed
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
   * @return Whether the indexDate field is set.
   */
  @java.lang.Override
  public boolean hasIndexDate() {
    return indexDate_ != null;
  }
  /**
   * <pre>
   *The date the base CPI was observed
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
   * @return The indexDate.
   */
  @java.lang.Override
  public fintekkers.models.util.LocalDate.LocalDateProto getIndexDate() {
    return indexDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : indexDate_;
  }
  /**
   * <pre>
   *The date the base CPI was observed
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getIndexDateOrBuilder() {
    return indexDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : indexDate_;
  }

  public static final int INFLATION_INDEX_TYPE_FIELD_NUMBER = 3;
  private int inflationIndexType_ = 0;
  /**
   * <pre>
   *Which inflation index (e.g. CPI_U)
   * </pre>
   *
   * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
   * @return The enum numeric value on the wire for inflationIndexType.
   */
  @java.lang.Override public int getInflationIndexTypeValue() {
    return inflationIndexType_;
  }
  /**
   * <pre>
   *Which inflation index (e.g. CPI_U)
   * </pre>
   *
   * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
   * @return The inflationIndexType.
   */
  @java.lang.Override public fintekkers.models.security.index.IndexTypeProto getInflationIndexType() {
    fintekkers.models.security.index.IndexTypeProto result = fintekkers.models.security.index.IndexTypeProto.forNumber(inflationIndexType_);
    return result == null ? fintekkers.models.security.index.IndexTypeProto.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseCpi_ != null) {
      output.writeMessage(1, getBaseCpi());
    }
    if (indexDate_ != null) {
      output.writeMessage(2, getIndexDate());
    }
    if (inflationIndexType_ != fintekkers.models.security.index.IndexTypeProto.UNKNOWN_INDEX_TYPE.getNumber()) {
      output.writeEnum(3, inflationIndexType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseCpi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseCpi());
    }
    if (indexDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getIndexDate());
    }
    if (inflationIndexType_ != fintekkers.models.security.index.IndexTypeProto.UNKNOWN_INDEX_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, inflationIndexType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.models.security.TipsExtensionProto)) {
      return super.equals(obj);
    }
    fintekkers.models.security.TipsExtensionProto other = (fintekkers.models.security.TipsExtensionProto) obj;

    if (hasBaseCpi() != other.hasBaseCpi()) return false;
    if (hasBaseCpi()) {
      if (!getBaseCpi()
          .equals(other.getBaseCpi())) return false;
    }
    if (hasIndexDate() != other.hasIndexDate()) return false;
    if (hasIndexDate()) {
      if (!getIndexDate()
          .equals(other.getIndexDate())) return false;
    }
    if (inflationIndexType_ != other.inflationIndexType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseCpi()) {
      hash = (37 * hash) + BASE_CPI_FIELD_NUMBER;
      hash = (53 * hash) + getBaseCpi().hashCode();
    }
    if (hasIndexDate()) {
      hash = (37 * hash) + INDEX_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getIndexDate().hashCode();
    }
    hash = (37 * hash) + INFLATION_INDEX_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + inflationIndexType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.security.TipsExtensionProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.TipsExtensionProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.TipsExtensionProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.models.security.TipsExtensionProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TIPS (Treasury Inflation-Protected Securities) extras.
   * Carries ONLY the TIPS-specific fields; shared bond fields live in
   * SecurityProto.bond_details. Populated when product_type == TIPS.
   * </pre>
   *
   * Protobuf type {@code fintekkers.models.security.TipsExtensionProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.models.security.TipsExtensionProto)
      fintekkers.models.security.TipsExtensionProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_TipsExtensionProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_TipsExtensionProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.models.security.TipsExtensionProto.class, fintekkers.models.security.TipsExtensionProto.Builder.class);
    }

    // Construct using fintekkers.models.security.TipsExtensionProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseCpi_ = null;
      if (baseCpiBuilder_ != null) {
        baseCpiBuilder_.dispose();
        baseCpiBuilder_ = null;
      }
      indexDate_ = null;
      if (indexDateBuilder_ != null) {
        indexDateBuilder_.dispose();
        indexDateBuilder_ = null;
      }
      inflationIndexType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.models.security.SecurityProtos.internal_static_fintekkers_models_security_TipsExtensionProto_descriptor;
    }

    @java.lang.Override
    public fintekkers.models.security.TipsExtensionProto getDefaultInstanceForType() {
      return fintekkers.models.security.TipsExtensionProto.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.models.security.TipsExtensionProto build() {
      fintekkers.models.security.TipsExtensionProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.models.security.TipsExtensionProto buildPartial() {
      fintekkers.models.security.TipsExtensionProto result = new fintekkers.models.security.TipsExtensionProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(fintekkers.models.security.TipsExtensionProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseCpi_ = baseCpiBuilder_ == null
            ? baseCpi_
            : baseCpiBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.indexDate_ = indexDateBuilder_ == null
            ? indexDate_
            : indexDateBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.inflationIndexType_ = inflationIndexType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.models.security.TipsExtensionProto) {
        return mergeFrom((fintekkers.models.security.TipsExtensionProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.models.security.TipsExtensionProto other) {
      if (other == fintekkers.models.security.TipsExtensionProto.getDefaultInstance()) return this;
      if (other.hasBaseCpi()) {
        mergeBaseCpi(other.getBaseCpi());
      }
      if (other.hasIndexDate()) {
        mergeIndexDate(other.getIndexDate());
      }
      if (other.inflationIndexType_ != 0) {
        setInflationIndexTypeValue(other.getInflationIndexTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseCpiFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getIndexDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              inflationIndexType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private fintekkers.models.util.DecimalValue.DecimalValueProto baseCpi_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> baseCpiBuilder_;
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     * @return Whether the baseCpi field is set.
     */
    public boolean hasBaseCpi() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     * @return The baseCpi.
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto getBaseCpi() {
      if (baseCpiBuilder_ == null) {
        return baseCpi_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : baseCpi_;
      } else {
        return baseCpiBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    public Builder setBaseCpi(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (baseCpiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseCpi_ = value;
      } else {
        baseCpiBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    public Builder setBaseCpi(
        fintekkers.models.util.DecimalValue.DecimalValueProto.Builder builderForValue) {
      if (baseCpiBuilder_ == null) {
        baseCpi_ = builderForValue.build();
      } else {
        baseCpiBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    public Builder mergeBaseCpi(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (baseCpiBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseCpi_ != null &&
          baseCpi_ != fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance()) {
          getBaseCpiBuilder().mergeFrom(value);
        } else {
          baseCpi_ = value;
        }
      } else {
        baseCpiBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    public Builder clearBaseCpi() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseCpi_ = null;
      if (baseCpiBuilder_ != null) {
        baseCpiBuilder_.dispose();
        baseCpiBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto.Builder getBaseCpiBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseCpiFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getBaseCpiOrBuilder() {
      if (baseCpiBuilder_ != null) {
        return baseCpiBuilder_.getMessageOrBuilder();
      } else {
        return baseCpi_ == null ?
            fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : baseCpi_;
      }
    }
    /**
     * <pre>
     *Reference CPI at bond issuance (e.g. 256.394)
     * </pre>
     *
     * <code>.fintekkers.models.util.DecimalValueProto base_cpi = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> 
        getBaseCpiFieldBuilder() {
      if (baseCpiBuilder_ == null) {
        baseCpiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder>(
                getBaseCpi(),
                getParentForChildren(),
                isClean());
        baseCpi_ = null;
      }
      return baseCpiBuilder_;
    }

    private fintekkers.models.util.LocalDate.LocalDateProto indexDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder> indexDateBuilder_;
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     * @return Whether the indexDate field is set.
     */
    public boolean hasIndexDate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     * @return The indexDate.
     */
    public fintekkers.models.util.LocalDate.LocalDateProto getIndexDate() {
      if (indexDateBuilder_ == null) {
        return indexDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : indexDate_;
      } else {
        return indexDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    public Builder setIndexDate(fintekkers.models.util.LocalDate.LocalDateProto value) {
      if (indexDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        indexDate_ = value;
      } else {
        indexDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    public Builder setIndexDate(
        fintekkers.models.util.LocalDate.LocalDateProto.Builder builderForValue) {
      if (indexDateBuilder_ == null) {
        indexDate_ = builderForValue.build();
      } else {
        indexDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    public Builder mergeIndexDate(fintekkers.models.util.LocalDate.LocalDateProto value) {
      if (indexDateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          indexDate_ != null &&
          indexDate_ != fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance()) {
          getIndexDateBuilder().mergeFrom(value);
        } else {
          indexDate_ = value;
        }
      } else {
        indexDateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    public Builder clearIndexDate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      indexDate_ = null;
      if (indexDateBuilder_ != null) {
        indexDateBuilder_.dispose();
        indexDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    public fintekkers.models.util.LocalDate.LocalDateProto.Builder getIndexDateBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getIndexDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    public fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getIndexDateOrBuilder() {
      if (indexDateBuilder_ != null) {
        return indexDateBuilder_.getMessageOrBuilder();
      } else {
        return indexDate_ == null ?
            fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : indexDate_;
      }
    }
    /**
     * <pre>
     *The date the base CPI was observed
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalDateProto index_date = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder> 
        getIndexDateFieldBuilder() {
      if (indexDateBuilder_ == null) {
        indexDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder>(
                getIndexDate(),
                getParentForChildren(),
                isClean());
        indexDate_ = null;
      }
      return indexDateBuilder_;
    }

    private int inflationIndexType_ = 0;
    /**
     * <pre>
     *Which inflation index (e.g. CPI_U)
     * </pre>
     *
     * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
     * @return The enum numeric value on the wire for inflationIndexType.
     */
    @java.lang.Override public int getInflationIndexTypeValue() {
      return inflationIndexType_;
    }
    /**
     * <pre>
     *Which inflation index (e.g. CPI_U)
     * </pre>
     *
     * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
     * @param value The enum numeric value on the wire for inflationIndexType to set.
     * @return This builder for chaining.
     */
    public Builder setInflationIndexTypeValue(int value) {
      inflationIndexType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Which inflation index (e.g. CPI_U)
     * </pre>
     *
     * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
     * @return The inflationIndexType.
     */
    @java.lang.Override
    public fintekkers.models.security.index.IndexTypeProto getInflationIndexType() {
      fintekkers.models.security.index.IndexTypeProto result = fintekkers.models.security.index.IndexTypeProto.forNumber(inflationIndexType_);
      return result == null ? fintekkers.models.security.index.IndexTypeProto.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *Which inflation index (e.g. CPI_U)
     * </pre>
     *
     * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
     * @param value The inflationIndexType to set.
     * @return This builder for chaining.
     */
    public Builder setInflationIndexType(fintekkers.models.security.index.IndexTypeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      inflationIndexType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Which inflation index (e.g. CPI_U)
     * </pre>
     *
     * <code>.fintekkers.models.security.index.IndexTypeProto inflation_index_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInflationIndexType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      inflationIndexType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.models.security.TipsExtensionProto)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.models.security.TipsExtensionProto)
  private static final fintekkers.models.security.TipsExtensionProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.models.security.TipsExtensionProto();
  }

  public static fintekkers.models.security.TipsExtensionProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TipsExtensionProto>
      PARSER = new com.google.protobuf.AbstractParser<TipsExtensionProto>() {
    @java.lang.Override
    public TipsExtensionProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TipsExtensionProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TipsExtensionProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.models.security.TipsExtensionProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

