// @generated by protobuf-ts 2.9.3 with parameter output_javascript_es2020
// @generated from protobuf file "msg-readme.proto" (syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.3 with parameter output_javascript_es2020
// @generated from protobuf file "msg-readme.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class Person$Type extends MessageType {
    constructor() {
        super("Person", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "years", kind: "scalar", jsonName: "baz", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "data", kind: "scalar", opt: true, T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Person
 */
export const Person = new Person$Type();
