// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/requests/util/delete_request.proto

package fintekkers.requests.util;

public interface DeleteRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fintekkers.requests.util.DeleteRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  java.lang.String getObjectClass();
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * The UUID of the entity to delete.
   * </pre>
   *
   * <code>.fintekkers.models.util.UUIDProto uuid = 10;</code>
   * @return Whether the uuid field is set.
   */
  boolean hasUuid();
  /**
   * <pre>
   * The UUID of the entity to delete.
   * </pre>
   *
   * <code>.fintekkers.models.util.UUIDProto uuid = 10;</code>
   * @return The uuid.
   */
  fintekkers.models.util.Uuid.UUIDProto getUuid();
  /**
   * <pre>
   * The UUID of the entity to delete.
   * </pre>
   *
   * <code>.fintekkers.models.util.UUIDProto uuid = 10;</code>
   */
  fintekkers.models.util.Uuid.UUIDProtoOrBuilder getUuidOrBuilder();

  /**
   * <pre>
   * The type of entity being deleted.
   * </pre>
   *
   * <code>.fintekkers.requests.util.EntityTypeProto entity_type = 11;</code>
   * @return The enum numeric value on the wire for entityType.
   */
  int getEntityTypeValue();
  /**
   * <pre>
   * The type of entity being deleted.
   * </pre>
   *
   * <code>.fintekkers.requests.util.EntityTypeProto entity_type = 11;</code>
   * @return The entityType.
   */
  fintekkers.requests.util.EntityTypeProto getEntityType();

  /**
   * <pre>
   * If true, return what would be deleted without actually deleting anything.
   * </pre>
   *
   * <code>bool dry_run = 20;</code>
   * @return The dryRun.
   */
  boolean getDryRun();

  /**
   * <pre>
   * If true, delete dependent entities in addition to the target entity.
   * Mutually exclusive with force.
   * </pre>
   *
   * <code>bool cascade = 21;</code>
   * @return The cascade.
   */
  boolean getCascade();

  /**
   * <pre>
   * If true, allow deletion even if the entity is referenced by other entities,
   * without deleting those references. Mutually exclusive with cascade.
   * </pre>
   *
   * <code>bool force = 22;</code>
   * @return The force.
   */
  boolean getForce();
}
