// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fintekkers/models/security/bond/issuance.proto

package fintekkers.models.security.bond;

/**
 * <pre>
 *Issuance proto contains the following:
 *- changes in outstanding quantities.
 *- auction
 *- auction date
 *- issue date (note: original issue date is found on the base security)
 *- announcement date
 *- pre-auction outstanding quantity
 *- offering amount
 *- auction type (e.g. single price)
 *- price (if single price auction)
 *- award details, i.e. below. The above should apply to corproate issuance also
 *&lt;PrimaryDealerTendered&gt;136650000000&lt;/PrimaryDealerTendered&gt;
 *&lt;PrimaryDealerAccepted&gt;32879650000&lt;/PrimaryDealerAccepted&gt;
 *&lt;DirectBidderTendered&gt;9525000000&lt;/DirectBidderTendered&gt;
 *&lt;DirectBidderAccepted&gt;3548785000&lt;/DirectBidderAccepted&gt;
 *&lt;IndirectBidderTendered&gt;9055736500&lt;/IndirectBidderTendered&gt;
 *&lt;IndirectBidderAccepted&gt;8145454000&lt;/IndirectBidderAccepted&gt;
 *&lt;CompetitiveTendered&gt;155230736500&lt;/CompetitiveTendered&gt;
 *&lt;CompetitiveAccepted&gt;44573889000&lt;/CompetitiveAccepted&gt;
 *&lt;NonCompetitiveAccepted&gt;326458500&lt;/NonCompetitiveAccepted&gt;
 *&lt;SOMATendered&gt;0&lt;/SOMATendered&gt;
 *&lt;SOMAAccepted&gt;0&lt;/SOMAAccepted&gt;
 *&lt;FIMATendered&gt;100000000&lt;/FIMATendered&gt;
 *&lt;FIMAAccepted&gt;100000000&lt;/FIMAAccepted&gt;
 *&lt;TotalTendered&gt;155657195000&lt;/TotalTendered&gt;
 *&lt;TotalAccepted&gt;45000347500&lt;/TotalAccepted&gt;
 *- tender offer
 *- ?
 * </pre>
 *
 * Protobuf type {@code fintekkers.models.security.bond.IssuanceProto}
 */
public final class IssuanceProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fintekkers.models.security.bond.IssuanceProto)
    IssuanceProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IssuanceProto.newBuilder() to construct.
  private IssuanceProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IssuanceProto() {
    objectClass_ = "";
    version_ = "";
    auctionType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IssuanceProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IssuanceProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            objectClass_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 50: {
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder subBuilder = null;
            if (asOf_ != null) {
              subBuilder = asOf_.toBuilder();
            }
            asOf_ = input.readMessage(fintekkers.models.util.LocalTimestamp.LocalTimestampProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(asOf_);
              asOf_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder subBuilder = null;
            if (validFrom_ != null) {
              subBuilder = validFrom_.toBuilder();
            }
            validFrom_ = input.readMessage(fintekkers.models.util.LocalTimestamp.LocalTimestampProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(validFrom_);
              validFrom_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder subBuilder = null;
            if (validTo_ != null) {
              subBuilder = validTo_.toBuilder();
            }
            validTo_ = input.readMessage(fintekkers.models.util.LocalTimestamp.LocalTimestampProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(validTo_);
              validTo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 162: {
            fintekkers.models.util.LocalDate.LocalDateProto.Builder subBuilder = null;
            if (auctionAnnouncementDate_ != null) {
              subBuilder = auctionAnnouncementDate_.toBuilder();
            }
            auctionAnnouncementDate_ = input.readMessage(fintekkers.models.util.LocalDate.LocalDateProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(auctionAnnouncementDate_);
              auctionAnnouncementDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 170: {
            fintekkers.models.util.LocalDate.LocalDateProto.Builder subBuilder = null;
            if (auctionIssueDate_ != null) {
              subBuilder = auctionIssueDate_.toBuilder();
            }
            auctionIssueDate_ = input.readMessage(fintekkers.models.util.LocalDate.LocalDateProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(auctionIssueDate_);
              auctionIssueDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 178: {
            fintekkers.models.util.DecimalValue.DecimalValueProto.Builder subBuilder = null;
            if (preauctionOutstandingQuantity_ != null) {
              subBuilder = preauctionOutstandingQuantity_.toBuilder();
            }
            preauctionOutstandingQuantity_ = input.readMessage(fintekkers.models.util.DecimalValue.DecimalValueProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(preauctionOutstandingQuantity_);
              preauctionOutstandingQuantity_ = subBuilder.buildPartial();
            }

            break;
          }
          case 186: {
            fintekkers.models.util.DecimalValue.DecimalValueProto.Builder subBuilder = null;
            if (auctionOfferingAmount_ != null) {
              subBuilder = auctionOfferingAmount_.toBuilder();
            }
            auctionOfferingAmount_ = input.readMessage(fintekkers.models.util.DecimalValue.DecimalValueProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(auctionOfferingAmount_);
              auctionOfferingAmount_ = subBuilder.buildPartial();
            }

            break;
          }
          case 192: {
            int rawValue = input.readEnum();

            auctionType_ = rawValue;
            break;
          }
          case 202: {
            fintekkers.models.util.DecimalValue.DecimalValueProto.Builder subBuilder = null;
            if (priceForSinglePriceAuction_ != null) {
              subBuilder = priceForSinglePriceAuction_.toBuilder();
            }
            priceForSinglePriceAuction_ = input.readMessage(fintekkers.models.util.DecimalValue.DecimalValueProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(priceForSinglePriceAuction_);
              priceForSinglePriceAuction_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return fintekkers.models.security.bond.IssuanceProtos.internal_static_fintekkers_models_security_bond_IssuanceProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return fintekkers.models.security.bond.IssuanceProtos.internal_static_fintekkers_models_security_bond_IssuanceProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fintekkers.models.security.bond.IssuanceProto.class, fintekkers.models.security.bond.IssuanceProto.Builder.class);
  }

  public static final int OBJECT_CLASS_FIELD_NUMBER = 1;
  private volatile java.lang.Object objectClass_;
  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  @java.lang.Override
  public java.lang.String getObjectClass() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectClass_ = s;
      return s;
    }
  }
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectClassBytes() {
    java.lang.Object ref = objectClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AS_OF_FIELD_NUMBER = 6;
  private fintekkers.models.util.LocalTimestamp.LocalTimestampProto asOf_;
  /**
   * <pre>
   *Primary Key not needed currently as these will be stored on the security object
   *   fintekkers.models.util.UUIDProto uuid = 5;
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
   * @return Whether the asOf field is set.
   */
  @java.lang.Override
  public boolean hasAsOf() {
    return asOf_ != null;
  }
  /**
   * <pre>
   *Primary Key not needed currently as these will be stored on the security object
   *   fintekkers.models.util.UUIDProto uuid = 5;
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
   * @return The asOf.
   */
  @java.lang.Override
  public fintekkers.models.util.LocalTimestamp.LocalTimestampProto getAsOf() {
    return asOf_ == null ? fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : asOf_;
  }
  /**
   * <pre>
   *Primary Key not needed currently as these will be stored on the security object
   *   fintekkers.models.util.UUIDProto uuid = 5;
   * </pre>
   *
   * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder getAsOfOrBuilder() {
    return getAsOf();
  }

  public static final int VALID_FROM_FIELD_NUMBER = 8;
  private fintekkers.models.util.LocalTimestamp.LocalTimestampProto validFrom_;
  /**
   * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
   * @return Whether the validFrom field is set.
   */
  @java.lang.Override
  public boolean hasValidFrom() {
    return validFrom_ != null;
  }
  /**
   * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
   * @return The validFrom.
   */
  @java.lang.Override
  public fintekkers.models.util.LocalTimestamp.LocalTimestampProto getValidFrom() {
    return validFrom_ == null ? fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : validFrom_;
  }
  /**
   * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder getValidFromOrBuilder() {
    return getValidFrom();
  }

  public static final int VALID_TO_FIELD_NUMBER = 9;
  private fintekkers.models.util.LocalTimestamp.LocalTimestampProto validTo_;
  /**
   * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
   * @return Whether the validTo field is set.
   */
  @java.lang.Override
  public boolean hasValidTo() {
    return validTo_ != null;
  }
  /**
   * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
   * @return The validTo.
   */
  @java.lang.Override
  public fintekkers.models.util.LocalTimestamp.LocalTimestampProto getValidTo() {
    return validTo_ == null ? fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : validTo_;
  }
  /**
   * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder getValidToOrBuilder() {
    return getValidTo();
  }

  public static final int AUCTION_ANNOUNCEMENT_DATE_FIELD_NUMBER = 20;
  private fintekkers.models.util.LocalDate.LocalDateProto auctionAnnouncementDate_;
  /**
   * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
   * @return Whether the auctionAnnouncementDate field is set.
   */
  @java.lang.Override
  public boolean hasAuctionAnnouncementDate() {
    return auctionAnnouncementDate_ != null;
  }
  /**
   * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
   * @return The auctionAnnouncementDate.
   */
  @java.lang.Override
  public fintekkers.models.util.LocalDate.LocalDateProto getAuctionAnnouncementDate() {
    return auctionAnnouncementDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : auctionAnnouncementDate_;
  }
  /**
   * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getAuctionAnnouncementDateOrBuilder() {
    return getAuctionAnnouncementDate();
  }

  public static final int AUCTION_ISSUE_DATE_FIELD_NUMBER = 21;
  private fintekkers.models.util.LocalDate.LocalDateProto auctionIssueDate_;
  /**
   * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
   * @return Whether the auctionIssueDate field is set.
   */
  @java.lang.Override
  public boolean hasAuctionIssueDate() {
    return auctionIssueDate_ != null;
  }
  /**
   * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
   * @return The auctionIssueDate.
   */
  @java.lang.Override
  public fintekkers.models.util.LocalDate.LocalDateProto getAuctionIssueDate() {
    return auctionIssueDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : auctionIssueDate_;
  }
  /**
   * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getAuctionIssueDateOrBuilder() {
    return getAuctionIssueDate();
  }

  public static final int PREAUCTION_OUTSTANDING_QUANTITY_FIELD_NUMBER = 22;
  private fintekkers.models.util.DecimalValue.DecimalValueProto preauctionOutstandingQuantity_;
  /**
   * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
   * @return Whether the preauctionOutstandingQuantity field is set.
   */
  @java.lang.Override
  public boolean hasPreauctionOutstandingQuantity() {
    return preauctionOutstandingQuantity_ != null;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
   * @return The preauctionOutstandingQuantity.
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProto getPreauctionOutstandingQuantity() {
    return preauctionOutstandingQuantity_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : preauctionOutstandingQuantity_;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getPreauctionOutstandingQuantityOrBuilder() {
    return getPreauctionOutstandingQuantity();
  }

  public static final int AUCTION_OFFERING_AMOUNT_FIELD_NUMBER = 23;
  private fintekkers.models.util.DecimalValue.DecimalValueProto auctionOfferingAmount_;
  /**
   * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
   * @return Whether the auctionOfferingAmount field is set.
   */
  @java.lang.Override
  public boolean hasAuctionOfferingAmount() {
    return auctionOfferingAmount_ != null;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
   * @return The auctionOfferingAmount.
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProto getAuctionOfferingAmount() {
    return auctionOfferingAmount_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : auctionOfferingAmount_;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getAuctionOfferingAmountOrBuilder() {
    return getAuctionOfferingAmount();
  }

  public static final int AUCTION_TYPE_FIELD_NUMBER = 24;
  private int auctionType_;
  /**
   * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
   * @return The enum numeric value on the wire for auctionType.
   */
  @java.lang.Override public int getAuctionTypeValue() {
    return auctionType_;
  }
  /**
   * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
   * @return The auctionType.
   */
  @java.lang.Override public fintekkers.models.security.bond.AuctionTypeProto getAuctionType() {
    @SuppressWarnings("deprecation")
    fintekkers.models.security.bond.AuctionTypeProto result = fintekkers.models.security.bond.AuctionTypeProto.valueOf(auctionType_);
    return result == null ? fintekkers.models.security.bond.AuctionTypeProto.UNRECOGNIZED : result;
  }

  public static final int PRICE_FOR_SINGLE_PRICE_AUCTION_FIELD_NUMBER = 25;
  private fintekkers.models.util.DecimalValue.DecimalValueProto priceForSinglePriceAuction_;
  /**
   * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
   * @return Whether the priceForSinglePriceAuction field is set.
   */
  @java.lang.Override
  public boolean hasPriceForSinglePriceAuction() {
    return priceForSinglePriceAuction_ != null;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
   * @return The priceForSinglePriceAuction.
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProto getPriceForSinglePriceAuction() {
    return priceForSinglePriceAuction_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : priceForSinglePriceAuction_;
  }
  /**
   * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
   */
  @java.lang.Override
  public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getPriceForSinglePriceAuctionOrBuilder() {
    return getPriceForSinglePriceAuction();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getObjectClassBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (asOf_ != null) {
      output.writeMessage(6, getAsOf());
    }
    if (validFrom_ != null) {
      output.writeMessage(8, getValidFrom());
    }
    if (validTo_ != null) {
      output.writeMessage(9, getValidTo());
    }
    if (auctionAnnouncementDate_ != null) {
      output.writeMessage(20, getAuctionAnnouncementDate());
    }
    if (auctionIssueDate_ != null) {
      output.writeMessage(21, getAuctionIssueDate());
    }
    if (preauctionOutstandingQuantity_ != null) {
      output.writeMessage(22, getPreauctionOutstandingQuantity());
    }
    if (auctionOfferingAmount_ != null) {
      output.writeMessage(23, getAuctionOfferingAmount());
    }
    if (auctionType_ != fintekkers.models.security.bond.AuctionTypeProto.UNKNOWN_AUCTION_TYPE.getNumber()) {
      output.writeEnum(24, auctionType_);
    }
    if (priceForSinglePriceAuction_ != null) {
      output.writeMessage(25, getPriceForSinglePriceAuction());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getObjectClassBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, objectClass_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (asOf_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAsOf());
    }
    if (validFrom_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getValidFrom());
    }
    if (validTo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getValidTo());
    }
    if (auctionAnnouncementDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getAuctionAnnouncementDate());
    }
    if (auctionIssueDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getAuctionIssueDate());
    }
    if (preauctionOutstandingQuantity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, getPreauctionOutstandingQuantity());
    }
    if (auctionOfferingAmount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(23, getAuctionOfferingAmount());
    }
    if (auctionType_ != fintekkers.models.security.bond.AuctionTypeProto.UNKNOWN_AUCTION_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(24, auctionType_);
    }
    if (priceForSinglePriceAuction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(25, getPriceForSinglePriceAuction());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fintekkers.models.security.bond.IssuanceProto)) {
      return super.equals(obj);
    }
    fintekkers.models.security.bond.IssuanceProto other = (fintekkers.models.security.bond.IssuanceProto) obj;

    if (!getObjectClass()
        .equals(other.getObjectClass())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasAsOf() != other.hasAsOf()) return false;
    if (hasAsOf()) {
      if (!getAsOf()
          .equals(other.getAsOf())) return false;
    }
    if (hasValidFrom() != other.hasValidFrom()) return false;
    if (hasValidFrom()) {
      if (!getValidFrom()
          .equals(other.getValidFrom())) return false;
    }
    if (hasValidTo() != other.hasValidTo()) return false;
    if (hasValidTo()) {
      if (!getValidTo()
          .equals(other.getValidTo())) return false;
    }
    if (hasAuctionAnnouncementDate() != other.hasAuctionAnnouncementDate()) return false;
    if (hasAuctionAnnouncementDate()) {
      if (!getAuctionAnnouncementDate()
          .equals(other.getAuctionAnnouncementDate())) return false;
    }
    if (hasAuctionIssueDate() != other.hasAuctionIssueDate()) return false;
    if (hasAuctionIssueDate()) {
      if (!getAuctionIssueDate()
          .equals(other.getAuctionIssueDate())) return false;
    }
    if (hasPreauctionOutstandingQuantity() != other.hasPreauctionOutstandingQuantity()) return false;
    if (hasPreauctionOutstandingQuantity()) {
      if (!getPreauctionOutstandingQuantity()
          .equals(other.getPreauctionOutstandingQuantity())) return false;
    }
    if (hasAuctionOfferingAmount() != other.hasAuctionOfferingAmount()) return false;
    if (hasAuctionOfferingAmount()) {
      if (!getAuctionOfferingAmount()
          .equals(other.getAuctionOfferingAmount())) return false;
    }
    if (auctionType_ != other.auctionType_) return false;
    if (hasPriceForSinglePriceAuction() != other.hasPriceForSinglePriceAuction()) return false;
    if (hasPriceForSinglePriceAuction()) {
      if (!getPriceForSinglePriceAuction()
          .equals(other.getPriceForSinglePriceAuction())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OBJECT_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getObjectClass().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasAsOf()) {
      hash = (37 * hash) + AS_OF_FIELD_NUMBER;
      hash = (53 * hash) + getAsOf().hashCode();
    }
    if (hasValidFrom()) {
      hash = (37 * hash) + VALID_FROM_FIELD_NUMBER;
      hash = (53 * hash) + getValidFrom().hashCode();
    }
    if (hasValidTo()) {
      hash = (37 * hash) + VALID_TO_FIELD_NUMBER;
      hash = (53 * hash) + getValidTo().hashCode();
    }
    if (hasAuctionAnnouncementDate()) {
      hash = (37 * hash) + AUCTION_ANNOUNCEMENT_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getAuctionAnnouncementDate().hashCode();
    }
    if (hasAuctionIssueDate()) {
      hash = (37 * hash) + AUCTION_ISSUE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getAuctionIssueDate().hashCode();
    }
    if (hasPreauctionOutstandingQuantity()) {
      hash = (37 * hash) + PREAUCTION_OUTSTANDING_QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getPreauctionOutstandingQuantity().hashCode();
    }
    if (hasAuctionOfferingAmount()) {
      hash = (37 * hash) + AUCTION_OFFERING_AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAuctionOfferingAmount().hashCode();
    }
    hash = (37 * hash) + AUCTION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + auctionType_;
    if (hasPriceForSinglePriceAuction()) {
      hash = (37 * hash) + PRICE_FOR_SINGLE_PRICE_AUCTION_FIELD_NUMBER;
      hash = (53 * hash) + getPriceForSinglePriceAuction().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fintekkers.models.security.bond.IssuanceProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fintekkers.models.security.bond.IssuanceProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Issuance proto contains the following:
   *- changes in outstanding quantities.
   *- auction
   *- auction date
   *- issue date (note: original issue date is found on the base security)
   *- announcement date
   *- pre-auction outstanding quantity
   *- offering amount
   *- auction type (e.g. single price)
   *- price (if single price auction)
   *- award details, i.e. below. The above should apply to corproate issuance also
   *&lt;PrimaryDealerTendered&gt;136650000000&lt;/PrimaryDealerTendered&gt;
   *&lt;PrimaryDealerAccepted&gt;32879650000&lt;/PrimaryDealerAccepted&gt;
   *&lt;DirectBidderTendered&gt;9525000000&lt;/DirectBidderTendered&gt;
   *&lt;DirectBidderAccepted&gt;3548785000&lt;/DirectBidderAccepted&gt;
   *&lt;IndirectBidderTendered&gt;9055736500&lt;/IndirectBidderTendered&gt;
   *&lt;IndirectBidderAccepted&gt;8145454000&lt;/IndirectBidderAccepted&gt;
   *&lt;CompetitiveTendered&gt;155230736500&lt;/CompetitiveTendered&gt;
   *&lt;CompetitiveAccepted&gt;44573889000&lt;/CompetitiveAccepted&gt;
   *&lt;NonCompetitiveAccepted&gt;326458500&lt;/NonCompetitiveAccepted&gt;
   *&lt;SOMATendered&gt;0&lt;/SOMATendered&gt;
   *&lt;SOMAAccepted&gt;0&lt;/SOMAAccepted&gt;
   *&lt;FIMATendered&gt;100000000&lt;/FIMATendered&gt;
   *&lt;FIMAAccepted&gt;100000000&lt;/FIMAAccepted&gt;
   *&lt;TotalTendered&gt;155657195000&lt;/TotalTendered&gt;
   *&lt;TotalAccepted&gt;45000347500&lt;/TotalAccepted&gt;
   *- tender offer
   *- ?
   * </pre>
   *
   * Protobuf type {@code fintekkers.models.security.bond.IssuanceProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fintekkers.models.security.bond.IssuanceProto)
      fintekkers.models.security.bond.IssuanceProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fintekkers.models.security.bond.IssuanceProtos.internal_static_fintekkers_models_security_bond_IssuanceProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fintekkers.models.security.bond.IssuanceProtos.internal_static_fintekkers_models_security_bond_IssuanceProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fintekkers.models.security.bond.IssuanceProto.class, fintekkers.models.security.bond.IssuanceProto.Builder.class);
    }

    // Construct using fintekkers.models.security.bond.IssuanceProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      objectClass_ = "";

      version_ = "";

      if (asOfBuilder_ == null) {
        asOf_ = null;
      } else {
        asOf_ = null;
        asOfBuilder_ = null;
      }
      if (validFromBuilder_ == null) {
        validFrom_ = null;
      } else {
        validFrom_ = null;
        validFromBuilder_ = null;
      }
      if (validToBuilder_ == null) {
        validTo_ = null;
      } else {
        validTo_ = null;
        validToBuilder_ = null;
      }
      if (auctionAnnouncementDateBuilder_ == null) {
        auctionAnnouncementDate_ = null;
      } else {
        auctionAnnouncementDate_ = null;
        auctionAnnouncementDateBuilder_ = null;
      }
      if (auctionIssueDateBuilder_ == null) {
        auctionIssueDate_ = null;
      } else {
        auctionIssueDate_ = null;
        auctionIssueDateBuilder_ = null;
      }
      if (preauctionOutstandingQuantityBuilder_ == null) {
        preauctionOutstandingQuantity_ = null;
      } else {
        preauctionOutstandingQuantity_ = null;
        preauctionOutstandingQuantityBuilder_ = null;
      }
      if (auctionOfferingAmountBuilder_ == null) {
        auctionOfferingAmount_ = null;
      } else {
        auctionOfferingAmount_ = null;
        auctionOfferingAmountBuilder_ = null;
      }
      auctionType_ = 0;

      if (priceForSinglePriceAuctionBuilder_ == null) {
        priceForSinglePriceAuction_ = null;
      } else {
        priceForSinglePriceAuction_ = null;
        priceForSinglePriceAuctionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return fintekkers.models.security.bond.IssuanceProtos.internal_static_fintekkers_models_security_bond_IssuanceProto_descriptor;
    }

    @java.lang.Override
    public fintekkers.models.security.bond.IssuanceProto getDefaultInstanceForType() {
      return fintekkers.models.security.bond.IssuanceProto.getDefaultInstance();
    }

    @java.lang.Override
    public fintekkers.models.security.bond.IssuanceProto build() {
      fintekkers.models.security.bond.IssuanceProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public fintekkers.models.security.bond.IssuanceProto buildPartial() {
      fintekkers.models.security.bond.IssuanceProto result = new fintekkers.models.security.bond.IssuanceProto(this);
      result.objectClass_ = objectClass_;
      result.version_ = version_;
      if (asOfBuilder_ == null) {
        result.asOf_ = asOf_;
      } else {
        result.asOf_ = asOfBuilder_.build();
      }
      if (validFromBuilder_ == null) {
        result.validFrom_ = validFrom_;
      } else {
        result.validFrom_ = validFromBuilder_.build();
      }
      if (validToBuilder_ == null) {
        result.validTo_ = validTo_;
      } else {
        result.validTo_ = validToBuilder_.build();
      }
      if (auctionAnnouncementDateBuilder_ == null) {
        result.auctionAnnouncementDate_ = auctionAnnouncementDate_;
      } else {
        result.auctionAnnouncementDate_ = auctionAnnouncementDateBuilder_.build();
      }
      if (auctionIssueDateBuilder_ == null) {
        result.auctionIssueDate_ = auctionIssueDate_;
      } else {
        result.auctionIssueDate_ = auctionIssueDateBuilder_.build();
      }
      if (preauctionOutstandingQuantityBuilder_ == null) {
        result.preauctionOutstandingQuantity_ = preauctionOutstandingQuantity_;
      } else {
        result.preauctionOutstandingQuantity_ = preauctionOutstandingQuantityBuilder_.build();
      }
      if (auctionOfferingAmountBuilder_ == null) {
        result.auctionOfferingAmount_ = auctionOfferingAmount_;
      } else {
        result.auctionOfferingAmount_ = auctionOfferingAmountBuilder_.build();
      }
      result.auctionType_ = auctionType_;
      if (priceForSinglePriceAuctionBuilder_ == null) {
        result.priceForSinglePriceAuction_ = priceForSinglePriceAuction_;
      } else {
        result.priceForSinglePriceAuction_ = priceForSinglePriceAuctionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fintekkers.models.security.bond.IssuanceProto) {
        return mergeFrom((fintekkers.models.security.bond.IssuanceProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fintekkers.models.security.bond.IssuanceProto other) {
      if (other == fintekkers.models.security.bond.IssuanceProto.getDefaultInstance()) return this;
      if (!other.getObjectClass().isEmpty()) {
        objectClass_ = other.objectClass_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasAsOf()) {
        mergeAsOf(other.getAsOf());
      }
      if (other.hasValidFrom()) {
        mergeValidFrom(other.getValidFrom());
      }
      if (other.hasValidTo()) {
        mergeValidTo(other.getValidTo());
      }
      if (other.hasAuctionAnnouncementDate()) {
        mergeAuctionAnnouncementDate(other.getAuctionAnnouncementDate());
      }
      if (other.hasAuctionIssueDate()) {
        mergeAuctionIssueDate(other.getAuctionIssueDate());
      }
      if (other.hasPreauctionOutstandingQuantity()) {
        mergePreauctionOutstandingQuantity(other.getPreauctionOutstandingQuantity());
      }
      if (other.hasAuctionOfferingAmount()) {
        mergeAuctionOfferingAmount(other.getAuctionOfferingAmount());
      }
      if (other.auctionType_ != 0) {
        setAuctionTypeValue(other.getAuctionTypeValue());
      }
      if (other.hasPriceForSinglePriceAuction()) {
        mergePriceForSinglePriceAuction(other.getPriceForSinglePriceAuction());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      fintekkers.models.security.bond.IssuanceProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (fintekkers.models.security.bond.IssuanceProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object objectClass_ = "";
    /**
     * <code>string object_class = 1;</code>
     * @return The objectClass.
     */
    public java.lang.String getObjectClass() {
      java.lang.Object ref = objectClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @return The bytes for objectClass.
     */
    public com.google.protobuf.ByteString
        getObjectClassBytes() {
      java.lang.Object ref = objectClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClass(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectClass() {
      
      objectClass_ = getDefaultInstance().getObjectClass();
      onChanged();
      return this;
    }
    /**
     * <code>string object_class = 1;</code>
     * @param value The bytes for objectClass to set.
     * @return This builder for chaining.
     */
    public Builder setObjectClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      objectClass_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private fintekkers.models.util.LocalTimestamp.LocalTimestampProto asOf_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder> asOfBuilder_;
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     * @return Whether the asOf field is set.
     */
    public boolean hasAsOf() {
      return asOfBuilder_ != null || asOf_ != null;
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     * @return The asOf.
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProto getAsOf() {
      if (asOfBuilder_ == null) {
        return asOf_ == null ? fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : asOf_;
      } else {
        return asOfBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    public Builder setAsOf(fintekkers.models.util.LocalTimestamp.LocalTimestampProto value) {
      if (asOfBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        asOf_ = value;
        onChanged();
      } else {
        asOfBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    public Builder setAsOf(
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder builderForValue) {
      if (asOfBuilder_ == null) {
        asOf_ = builderForValue.build();
        onChanged();
      } else {
        asOfBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    public Builder mergeAsOf(fintekkers.models.util.LocalTimestamp.LocalTimestampProto value) {
      if (asOfBuilder_ == null) {
        if (asOf_ != null) {
          asOf_ =
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.newBuilder(asOf_).mergeFrom(value).buildPartial();
        } else {
          asOf_ = value;
        }
        onChanged();
      } else {
        asOfBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    public Builder clearAsOf() {
      if (asOfBuilder_ == null) {
        asOf_ = null;
        onChanged();
      } else {
        asOf_ = null;
        asOfBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder getAsOfBuilder() {
      
      onChanged();
      return getAsOfFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder getAsOfOrBuilder() {
      if (asOfBuilder_ != null) {
        return asOfBuilder_.getMessageOrBuilder();
      } else {
        return asOf_ == null ?
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : asOf_;
      }
    }
    /**
     * <pre>
     *Primary Key not needed currently as these will be stored on the security object
     *   fintekkers.models.util.UUIDProto uuid = 5;
     * </pre>
     *
     * <code>.fintekkers.models.util.LocalTimestampProto as_of = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder> 
        getAsOfFieldBuilder() {
      if (asOfBuilder_ == null) {
        asOfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder>(
                getAsOf(),
                getParentForChildren(),
                isClean());
        asOf_ = null;
      }
      return asOfBuilder_;
    }

    private fintekkers.models.util.LocalTimestamp.LocalTimestampProto validFrom_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder> validFromBuilder_;
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     * @return Whether the validFrom field is set.
     */
    public boolean hasValidFrom() {
      return validFromBuilder_ != null || validFrom_ != null;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     * @return The validFrom.
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProto getValidFrom() {
      if (validFromBuilder_ == null) {
        return validFrom_ == null ? fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : validFrom_;
      } else {
        return validFromBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    public Builder setValidFrom(fintekkers.models.util.LocalTimestamp.LocalTimestampProto value) {
      if (validFromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        validFrom_ = value;
        onChanged();
      } else {
        validFromBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    public Builder setValidFrom(
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder builderForValue) {
      if (validFromBuilder_ == null) {
        validFrom_ = builderForValue.build();
        onChanged();
      } else {
        validFromBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    public Builder mergeValidFrom(fintekkers.models.util.LocalTimestamp.LocalTimestampProto value) {
      if (validFromBuilder_ == null) {
        if (validFrom_ != null) {
          validFrom_ =
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.newBuilder(validFrom_).mergeFrom(value).buildPartial();
        } else {
          validFrom_ = value;
        }
        onChanged();
      } else {
        validFromBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    public Builder clearValidFrom() {
      if (validFromBuilder_ == null) {
        validFrom_ = null;
        onChanged();
      } else {
        validFrom_ = null;
        validFromBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder getValidFromBuilder() {
      
      onChanged();
      return getValidFromFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder getValidFromOrBuilder() {
      if (validFromBuilder_ != null) {
        return validFromBuilder_.getMessageOrBuilder();
      } else {
        return validFrom_ == null ?
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : validFrom_;
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_from = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder> 
        getValidFromFieldBuilder() {
      if (validFromBuilder_ == null) {
        validFromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder>(
                getValidFrom(),
                getParentForChildren(),
                isClean());
        validFrom_ = null;
      }
      return validFromBuilder_;
    }

    private fintekkers.models.util.LocalTimestamp.LocalTimestampProto validTo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder> validToBuilder_;
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     * @return Whether the validTo field is set.
     */
    public boolean hasValidTo() {
      return validToBuilder_ != null || validTo_ != null;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     * @return The validTo.
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProto getValidTo() {
      if (validToBuilder_ == null) {
        return validTo_ == null ? fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : validTo_;
      } else {
        return validToBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    public Builder setValidTo(fintekkers.models.util.LocalTimestamp.LocalTimestampProto value) {
      if (validToBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        validTo_ = value;
        onChanged();
      } else {
        validToBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    public Builder setValidTo(
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder builderForValue) {
      if (validToBuilder_ == null) {
        validTo_ = builderForValue.build();
        onChanged();
      } else {
        validToBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    public Builder mergeValidTo(fintekkers.models.util.LocalTimestamp.LocalTimestampProto value) {
      if (validToBuilder_ == null) {
        if (validTo_ != null) {
          validTo_ =
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.newBuilder(validTo_).mergeFrom(value).buildPartial();
        } else {
          validTo_ = value;
        }
        onChanged();
      } else {
        validToBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    public Builder clearValidTo() {
      if (validToBuilder_ == null) {
        validTo_ = null;
        onChanged();
      } else {
        validTo_ = null;
        validToBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder getValidToBuilder() {
      
      onChanged();
      return getValidToFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    public fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder getValidToOrBuilder() {
      if (validToBuilder_ != null) {
        return validToBuilder_.getMessageOrBuilder();
      } else {
        return validTo_ == null ?
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto.getDefaultInstance() : validTo_;
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalTimestampProto valid_to = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder> 
        getValidToFieldBuilder() {
      if (validToBuilder_ == null) {
        validToBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.LocalTimestamp.LocalTimestampProto, fintekkers.models.util.LocalTimestamp.LocalTimestampProto.Builder, fintekkers.models.util.LocalTimestamp.LocalTimestampProtoOrBuilder>(
                getValidTo(),
                getParentForChildren(),
                isClean());
        validTo_ = null;
      }
      return validToBuilder_;
    }

    private fintekkers.models.util.LocalDate.LocalDateProto auctionAnnouncementDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder> auctionAnnouncementDateBuilder_;
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     * @return Whether the auctionAnnouncementDate field is set.
     */
    public boolean hasAuctionAnnouncementDate() {
      return auctionAnnouncementDateBuilder_ != null || auctionAnnouncementDate_ != null;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     * @return The auctionAnnouncementDate.
     */
    public fintekkers.models.util.LocalDate.LocalDateProto getAuctionAnnouncementDate() {
      if (auctionAnnouncementDateBuilder_ == null) {
        return auctionAnnouncementDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : auctionAnnouncementDate_;
      } else {
        return auctionAnnouncementDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    public Builder setAuctionAnnouncementDate(fintekkers.models.util.LocalDate.LocalDateProto value) {
      if (auctionAnnouncementDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        auctionAnnouncementDate_ = value;
        onChanged();
      } else {
        auctionAnnouncementDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    public Builder setAuctionAnnouncementDate(
        fintekkers.models.util.LocalDate.LocalDateProto.Builder builderForValue) {
      if (auctionAnnouncementDateBuilder_ == null) {
        auctionAnnouncementDate_ = builderForValue.build();
        onChanged();
      } else {
        auctionAnnouncementDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    public Builder mergeAuctionAnnouncementDate(fintekkers.models.util.LocalDate.LocalDateProto value) {
      if (auctionAnnouncementDateBuilder_ == null) {
        if (auctionAnnouncementDate_ != null) {
          auctionAnnouncementDate_ =
            fintekkers.models.util.LocalDate.LocalDateProto.newBuilder(auctionAnnouncementDate_).mergeFrom(value).buildPartial();
        } else {
          auctionAnnouncementDate_ = value;
        }
        onChanged();
      } else {
        auctionAnnouncementDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    public Builder clearAuctionAnnouncementDate() {
      if (auctionAnnouncementDateBuilder_ == null) {
        auctionAnnouncementDate_ = null;
        onChanged();
      } else {
        auctionAnnouncementDate_ = null;
        auctionAnnouncementDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    public fintekkers.models.util.LocalDate.LocalDateProto.Builder getAuctionAnnouncementDateBuilder() {
      
      onChanged();
      return getAuctionAnnouncementDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    public fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getAuctionAnnouncementDateOrBuilder() {
      if (auctionAnnouncementDateBuilder_ != null) {
        return auctionAnnouncementDateBuilder_.getMessageOrBuilder();
      } else {
        return auctionAnnouncementDate_ == null ?
            fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : auctionAnnouncementDate_;
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_announcement_date = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder> 
        getAuctionAnnouncementDateFieldBuilder() {
      if (auctionAnnouncementDateBuilder_ == null) {
        auctionAnnouncementDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder>(
                getAuctionAnnouncementDate(),
                getParentForChildren(),
                isClean());
        auctionAnnouncementDate_ = null;
      }
      return auctionAnnouncementDateBuilder_;
    }

    private fintekkers.models.util.LocalDate.LocalDateProto auctionIssueDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder> auctionIssueDateBuilder_;
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     * @return Whether the auctionIssueDate field is set.
     */
    public boolean hasAuctionIssueDate() {
      return auctionIssueDateBuilder_ != null || auctionIssueDate_ != null;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     * @return The auctionIssueDate.
     */
    public fintekkers.models.util.LocalDate.LocalDateProto getAuctionIssueDate() {
      if (auctionIssueDateBuilder_ == null) {
        return auctionIssueDate_ == null ? fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : auctionIssueDate_;
      } else {
        return auctionIssueDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    public Builder setAuctionIssueDate(fintekkers.models.util.LocalDate.LocalDateProto value) {
      if (auctionIssueDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        auctionIssueDate_ = value;
        onChanged();
      } else {
        auctionIssueDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    public Builder setAuctionIssueDate(
        fintekkers.models.util.LocalDate.LocalDateProto.Builder builderForValue) {
      if (auctionIssueDateBuilder_ == null) {
        auctionIssueDate_ = builderForValue.build();
        onChanged();
      } else {
        auctionIssueDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    public Builder mergeAuctionIssueDate(fintekkers.models.util.LocalDate.LocalDateProto value) {
      if (auctionIssueDateBuilder_ == null) {
        if (auctionIssueDate_ != null) {
          auctionIssueDate_ =
            fintekkers.models.util.LocalDate.LocalDateProto.newBuilder(auctionIssueDate_).mergeFrom(value).buildPartial();
        } else {
          auctionIssueDate_ = value;
        }
        onChanged();
      } else {
        auctionIssueDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    public Builder clearAuctionIssueDate() {
      if (auctionIssueDateBuilder_ == null) {
        auctionIssueDate_ = null;
        onChanged();
      } else {
        auctionIssueDate_ = null;
        auctionIssueDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    public fintekkers.models.util.LocalDate.LocalDateProto.Builder getAuctionIssueDateBuilder() {
      
      onChanged();
      return getAuctionIssueDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    public fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder getAuctionIssueDateOrBuilder() {
      if (auctionIssueDateBuilder_ != null) {
        return auctionIssueDateBuilder_.getMessageOrBuilder();
      } else {
        return auctionIssueDate_ == null ?
            fintekkers.models.util.LocalDate.LocalDateProto.getDefaultInstance() : auctionIssueDate_;
      }
    }
    /**
     * <code>.fintekkers.models.util.LocalDateProto auction_issue_date = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder> 
        getAuctionIssueDateFieldBuilder() {
      if (auctionIssueDateBuilder_ == null) {
        auctionIssueDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.LocalDate.LocalDateProto, fintekkers.models.util.LocalDate.LocalDateProto.Builder, fintekkers.models.util.LocalDate.LocalDateProtoOrBuilder>(
                getAuctionIssueDate(),
                getParentForChildren(),
                isClean());
        auctionIssueDate_ = null;
      }
      return auctionIssueDateBuilder_;
    }

    private fintekkers.models.util.DecimalValue.DecimalValueProto preauctionOutstandingQuantity_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> preauctionOutstandingQuantityBuilder_;
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     * @return Whether the preauctionOutstandingQuantity field is set.
     */
    public boolean hasPreauctionOutstandingQuantity() {
      return preauctionOutstandingQuantityBuilder_ != null || preauctionOutstandingQuantity_ != null;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     * @return The preauctionOutstandingQuantity.
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto getPreauctionOutstandingQuantity() {
      if (preauctionOutstandingQuantityBuilder_ == null) {
        return preauctionOutstandingQuantity_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : preauctionOutstandingQuantity_;
      } else {
        return preauctionOutstandingQuantityBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    public Builder setPreauctionOutstandingQuantity(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (preauctionOutstandingQuantityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        preauctionOutstandingQuantity_ = value;
        onChanged();
      } else {
        preauctionOutstandingQuantityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    public Builder setPreauctionOutstandingQuantity(
        fintekkers.models.util.DecimalValue.DecimalValueProto.Builder builderForValue) {
      if (preauctionOutstandingQuantityBuilder_ == null) {
        preauctionOutstandingQuantity_ = builderForValue.build();
        onChanged();
      } else {
        preauctionOutstandingQuantityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    public Builder mergePreauctionOutstandingQuantity(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (preauctionOutstandingQuantityBuilder_ == null) {
        if (preauctionOutstandingQuantity_ != null) {
          preauctionOutstandingQuantity_ =
            fintekkers.models.util.DecimalValue.DecimalValueProto.newBuilder(preauctionOutstandingQuantity_).mergeFrom(value).buildPartial();
        } else {
          preauctionOutstandingQuantity_ = value;
        }
        onChanged();
      } else {
        preauctionOutstandingQuantityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    public Builder clearPreauctionOutstandingQuantity() {
      if (preauctionOutstandingQuantityBuilder_ == null) {
        preauctionOutstandingQuantity_ = null;
        onChanged();
      } else {
        preauctionOutstandingQuantity_ = null;
        preauctionOutstandingQuantityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto.Builder getPreauctionOutstandingQuantityBuilder() {
      
      onChanged();
      return getPreauctionOutstandingQuantityFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getPreauctionOutstandingQuantityOrBuilder() {
      if (preauctionOutstandingQuantityBuilder_ != null) {
        return preauctionOutstandingQuantityBuilder_.getMessageOrBuilder();
      } else {
        return preauctionOutstandingQuantity_ == null ?
            fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : preauctionOutstandingQuantity_;
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto preauction_outstanding_quantity = 22;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> 
        getPreauctionOutstandingQuantityFieldBuilder() {
      if (preauctionOutstandingQuantityBuilder_ == null) {
        preauctionOutstandingQuantityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder>(
                getPreauctionOutstandingQuantity(),
                getParentForChildren(),
                isClean());
        preauctionOutstandingQuantity_ = null;
      }
      return preauctionOutstandingQuantityBuilder_;
    }

    private fintekkers.models.util.DecimalValue.DecimalValueProto auctionOfferingAmount_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> auctionOfferingAmountBuilder_;
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     * @return Whether the auctionOfferingAmount field is set.
     */
    public boolean hasAuctionOfferingAmount() {
      return auctionOfferingAmountBuilder_ != null || auctionOfferingAmount_ != null;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     * @return The auctionOfferingAmount.
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto getAuctionOfferingAmount() {
      if (auctionOfferingAmountBuilder_ == null) {
        return auctionOfferingAmount_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : auctionOfferingAmount_;
      } else {
        return auctionOfferingAmountBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    public Builder setAuctionOfferingAmount(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (auctionOfferingAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        auctionOfferingAmount_ = value;
        onChanged();
      } else {
        auctionOfferingAmountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    public Builder setAuctionOfferingAmount(
        fintekkers.models.util.DecimalValue.DecimalValueProto.Builder builderForValue) {
      if (auctionOfferingAmountBuilder_ == null) {
        auctionOfferingAmount_ = builderForValue.build();
        onChanged();
      } else {
        auctionOfferingAmountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    public Builder mergeAuctionOfferingAmount(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (auctionOfferingAmountBuilder_ == null) {
        if (auctionOfferingAmount_ != null) {
          auctionOfferingAmount_ =
            fintekkers.models.util.DecimalValue.DecimalValueProto.newBuilder(auctionOfferingAmount_).mergeFrom(value).buildPartial();
        } else {
          auctionOfferingAmount_ = value;
        }
        onChanged();
      } else {
        auctionOfferingAmountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    public Builder clearAuctionOfferingAmount() {
      if (auctionOfferingAmountBuilder_ == null) {
        auctionOfferingAmount_ = null;
        onChanged();
      } else {
        auctionOfferingAmount_ = null;
        auctionOfferingAmountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto.Builder getAuctionOfferingAmountBuilder() {
      
      onChanged();
      return getAuctionOfferingAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getAuctionOfferingAmountOrBuilder() {
      if (auctionOfferingAmountBuilder_ != null) {
        return auctionOfferingAmountBuilder_.getMessageOrBuilder();
      } else {
        return auctionOfferingAmount_ == null ?
            fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : auctionOfferingAmount_;
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto auction_offering_amount = 23;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> 
        getAuctionOfferingAmountFieldBuilder() {
      if (auctionOfferingAmountBuilder_ == null) {
        auctionOfferingAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder>(
                getAuctionOfferingAmount(),
                getParentForChildren(),
                isClean());
        auctionOfferingAmount_ = null;
      }
      return auctionOfferingAmountBuilder_;
    }

    private int auctionType_ = 0;
    /**
     * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
     * @return The enum numeric value on the wire for auctionType.
     */
    @java.lang.Override public int getAuctionTypeValue() {
      return auctionType_;
    }
    /**
     * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
     * @param value The enum numeric value on the wire for auctionType to set.
     * @return This builder for chaining.
     */
    public Builder setAuctionTypeValue(int value) {
      
      auctionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
     * @return The auctionType.
     */
    @java.lang.Override
    public fintekkers.models.security.bond.AuctionTypeProto getAuctionType() {
      @SuppressWarnings("deprecation")
      fintekkers.models.security.bond.AuctionTypeProto result = fintekkers.models.security.bond.AuctionTypeProto.valueOf(auctionType_);
      return result == null ? fintekkers.models.security.bond.AuctionTypeProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
     * @param value The auctionType to set.
     * @return This builder for chaining.
     */
    public Builder setAuctionType(fintekkers.models.security.bond.AuctionTypeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      auctionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.fintekkers.models.security.bond.AuctionTypeProto auction_type = 24;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuctionType() {
      
      auctionType_ = 0;
      onChanged();
      return this;
    }

    private fintekkers.models.util.DecimalValue.DecimalValueProto priceForSinglePriceAuction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> priceForSinglePriceAuctionBuilder_;
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     * @return Whether the priceForSinglePriceAuction field is set.
     */
    public boolean hasPriceForSinglePriceAuction() {
      return priceForSinglePriceAuctionBuilder_ != null || priceForSinglePriceAuction_ != null;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     * @return The priceForSinglePriceAuction.
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto getPriceForSinglePriceAuction() {
      if (priceForSinglePriceAuctionBuilder_ == null) {
        return priceForSinglePriceAuction_ == null ? fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : priceForSinglePriceAuction_;
      } else {
        return priceForSinglePriceAuctionBuilder_.getMessage();
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    public Builder setPriceForSinglePriceAuction(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (priceForSinglePriceAuctionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        priceForSinglePriceAuction_ = value;
        onChanged();
      } else {
        priceForSinglePriceAuctionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    public Builder setPriceForSinglePriceAuction(
        fintekkers.models.util.DecimalValue.DecimalValueProto.Builder builderForValue) {
      if (priceForSinglePriceAuctionBuilder_ == null) {
        priceForSinglePriceAuction_ = builderForValue.build();
        onChanged();
      } else {
        priceForSinglePriceAuctionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    public Builder mergePriceForSinglePriceAuction(fintekkers.models.util.DecimalValue.DecimalValueProto value) {
      if (priceForSinglePriceAuctionBuilder_ == null) {
        if (priceForSinglePriceAuction_ != null) {
          priceForSinglePriceAuction_ =
            fintekkers.models.util.DecimalValue.DecimalValueProto.newBuilder(priceForSinglePriceAuction_).mergeFrom(value).buildPartial();
        } else {
          priceForSinglePriceAuction_ = value;
        }
        onChanged();
      } else {
        priceForSinglePriceAuctionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    public Builder clearPriceForSinglePriceAuction() {
      if (priceForSinglePriceAuctionBuilder_ == null) {
        priceForSinglePriceAuction_ = null;
        onChanged();
      } else {
        priceForSinglePriceAuction_ = null;
        priceForSinglePriceAuctionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProto.Builder getPriceForSinglePriceAuctionBuilder() {
      
      onChanged();
      return getPriceForSinglePriceAuctionFieldBuilder().getBuilder();
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    public fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder getPriceForSinglePriceAuctionOrBuilder() {
      if (priceForSinglePriceAuctionBuilder_ != null) {
        return priceForSinglePriceAuctionBuilder_.getMessageOrBuilder();
      } else {
        return priceForSinglePriceAuction_ == null ?
            fintekkers.models.util.DecimalValue.DecimalValueProto.getDefaultInstance() : priceForSinglePriceAuction_;
      }
    }
    /**
     * <code>.fintekkers.models.util.DecimalValueProto price_for_single_price_auction = 25;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder> 
        getPriceForSinglePriceAuctionFieldBuilder() {
      if (priceForSinglePriceAuctionBuilder_ == null) {
        priceForSinglePriceAuctionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            fintekkers.models.util.DecimalValue.DecimalValueProto, fintekkers.models.util.DecimalValue.DecimalValueProto.Builder, fintekkers.models.util.DecimalValue.DecimalValueProtoOrBuilder>(
                getPriceForSinglePriceAuction(),
                getParentForChildren(),
                isClean());
        priceForSinglePriceAuction_ = null;
      }
      return priceForSinglePriceAuctionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fintekkers.models.security.bond.IssuanceProto)
  }

  // @@protoc_insertion_point(class_scope:fintekkers.models.security.bond.IssuanceProto)
  private static final fintekkers.models.security.bond.IssuanceProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fintekkers.models.security.bond.IssuanceProto();
  }

  public static fintekkers.models.security.bond.IssuanceProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IssuanceProto>
      PARSER = new com.google.protobuf.AbstractParser<IssuanceProto>() {
    @java.lang.Override
    public IssuanceProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IssuanceProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IssuanceProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IssuanceProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public fintekkers.models.security.bond.IssuanceProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

